open-rmf/rmf-web

- src/components/schedule-visualizer/robot-trajectory.test.tsx
I got this error when I ran the tests: `TypeError: Cannot read property 'includes' of undefined`
I fixed the error updating the robot-trajectory test
> Fixed robot-trajectory test

- src/components/schedule-visualizer/robot.tsx
> Added name to robots.

- src/mock/data/building-map-airport.ts
- src/mock/data/building-map-office.ts
- src/mock/data/building-map.ts
* Drawed (mocked) doors to the airport map.
* Refactor structure of building map.
On our mock data, the airport's it's now "on the second floor of the office," I think that's ok for now, for demo purposes. So now the office and the airport will share the elevator, and they will be in an incorrect position at the airport. This is no logically correct but with that configuration, one can check how the component looks in both maps and test the multilevel components. which is cool.
> Added doors to the airport map

- e2e/startBackend.ts
- package.json
* Added `start:backend` command. The purpose of this is to serve the backend.
> Add start local backend script

- src/components/robot-item.tsx
Fixes #83 
Removed the delivery tab from the Robot Panel
> Removed the delivery tab from the Robot Panel

- README.md
- src/mock/data/fleets.ts
- src/mock/data/places.ts
- src/mock/data/trajectories.json
Related to https://github.com/osrf/rmf_demos/pull/115
Renamed Magni to TinyRobot, MiR100 to DeliveryRobot
> Renamed instances of Magni to TinyRobot

- .github/workflows/unit-test.yml
- README.md
- package.json
Excluded unnecessary files in the test coverage so that it is easier to read through the report. Also included a command to run the report to make it easy to generate the report.
Added this fix so that in future, it is easier to see which conditions have yet to be tested when we are writing unit tests.
> ignore files in test coverage and add new coverage command

- src/components/dashboard.tsx
- src/components/negotiations-panel.tsx
- src/components/tests/__snapshots__/negotiations-panel.test.tsx.snap
- src/components/tests/negotiations-panel.test.tsx
- src/negotiation-status-manager.ts
using a timestamp for React.memo() on NegotiationPanel to work
before:
after:
> [ready] Negotiation panel optimization

- src/components/loop-form.tsx
- src/components/negotiations-panel.tsx
- src/components/schedule-visualizer/tests/__snapshots__/robot-trajectories-overlay.test.tsx.snap
- src/components/schedule-visualizer/tests/__snapshots__/robot-trajectory.test.tsx.snap
- src/components/tests/__snapshots__/negotiations-panel.test.tsx.snap
- src/mock/data/trajectories.json
- src/robot-trajectory-manager.ts
- src/stories/baseComponents/utils-default-traj.tsx
- src/stories/baseComponents/utils-trajectory.tsx
~~depends on https://github.com/osrf/rmf_demos/pull/136~~ merged!
~~waiting for #80~~ merged!
- crash fix
- negotiation trajectories now show up on multilevel
run `ros2 launch demos clinic.launch.xml` instead of the office demo
> [ready] fixes/support for multilevel clinic demo

- .github/workflows/codecov.yml
- codecov.yml
Remove codecov in github checks..
Added a codecov file with necessary configuration.
What are some other files that can be ignored? Do we need the state-managers to run in the unit tests since I suppose they will be covered in the e2e tests?
> remove checks

- packages/dashboard/e2e/tests/negotiations.test.ts
- packages/dashboard/e2e/tests/utils.ts
Added request loop to e2e utils functions.
> Added requestLoop to e2e utils function.

- packages/dashboard/src/components/dashboard.tsx
Unused Dashboard tour components and tour props is causing build to fail.
Remove the unused components
> remove unused component

- packages/react-components/stories/benchmarks/robots.stories.tsx
fix robot benchmarks updating more than necessary
> fix robot benchmarks updating more than necessary

- packages/react-components/lib/omni-panel.tsx
- packages/react-components/stories/omni-panel.stories.tsx
> fix omnipanel scrolling

- .github/workflows/pull-requests.yml
- packages/react-components/.eslintignore
- packages/react-components/package.json
- packages/react-components/stories/benchmarks/robots.stories.tsx
- packages/react-components/stories/dialog.stories.tsx
- packages/react-components/stories/door-accordion.stories.tsx
- packages/react-components/stories/lift-accordion.stories.tsx
- packages/react-components/stories/trajectory-marker.stories.tsx
- packages/react-components/stories/tsconfig.json
Perform test build and typechecks for storybook on ci.
> ci(react-components): type checks for stories

- packages/dashboard/.gitignore
> ignore .eslintcache

- .gitignore
- README.md
Adds top-level instructions to help a new user install the required dependencies like nvm/npm/node and docker.
Just adds a README and slightly tweaks the gitignore to ignore python cache
> Update top-level readme

- packages/dashboard/src/components/dashboard-drawers.tsx
- packages/dashboard/src/components/dashboard.tsx
- packages/dashboard/src/components/reducers/main-menu-reducer.tsx
- packages/dashboard/src/components/reducers/tests/main-menu-reducer.test.tsx
Currently, the tour state is cached in localStorage as false, hence it is trying to show the tourstate component which has been removed for now. 
Removed tourState conditional for map loading and from the localStorage.
> fix tour state

- packages/dashboard/README.md
- packages/dashboard/e2e/env.sh
- packages/dashboard/src/app-config.ts
- packages/dashboard/src/components/app.tsx
- packages/dashboard/src/components/auth/authenticator.ts
- packages/dashboard/src/react-app-env.d.ts
- packages/dashboard/src/util/url.ts
allows dashboard to be hosted on any path
> dashboard: allows dashboard to be hosted on any path

- packages/ros2-bridge/src/authenticator.ts
- packages/ros2-bridge/src/logger.ts
- packages/ros2-bridge/src/plugins/ros2/index.ts
- packages/ros2-bridge/src/rpc-middleware.ts
- packages/ros2-bridge/src/tests/rpc-middleware.test.ts
- packages/ros2-bridge/src/tests/websocket-connect.test.ts
- packages/ros2-bridge/src/websocket-connect.ts
adds a bunch of new logs to the ros2 bridge server
> Ros2 bridge/more logging

- .github/workflows/nightly.yml
- .github/workflows/pull-requests.yml
> ci: fix coverage

- .github/pull_request_template.md
Add some guidelines on what kind of descriptions should a PR include. Make some of the templates like `fixes #` and `[Describe your changes]` a comment so that it is more obvious they should not be part of the pr message.
> ci: update pr template

- README.md
Signed-off-by: Morgan Quigley <morgan@osrfoundation.org>
Just an update to the installation README about adding the user to the `docker` group.
> add note about using the docker group and perhaps rebooting

- .github/workflows/api-server.yml
- .github/workflows/dashboard.yml
- .github/workflows/e2e.yml
- .github/workflows/react-components.yml
- .github/workflows/ros2-bridge.yml
> ci: install pipenv

- packages/api-server/.coveragerc
> api-server: ignore coverage for test files

- README.md
Fixes #232 
Added the recommended npm versions to use on the README located in the root folder.
> root:Updated readme with the npm version recommendation

- .github/workflows/dashboard.yml
- packages/dashboard/src/components/schedule-visualizer/dispensers-overlay.tsx
- packages/dashboard/src/components/schedule-visualizer/robots-overlay.tsx
- packages/dashboard/src/components/schedule-visualizer/tests/dispensers-overlay.test.tsx
- packages/dashboard/src/components/schedule-visualizer/tests/robots-overlay.test.tsx
might be related to #237, also added a path to github workflows to run dashboard tests when react-component changes, this should help prevent similar issues in the future.
> dashboard: fix tests by using a fake marker

- .github/workflows/api-server.yml
- packages/dashboard/e2e/docker/e2e/Dockerfile
- packages/dashboard/e2e/docker/rmf/Dockerfile
> ci: update dockerfile to build from the new open-rmf repos

- packages/dashboard/src/components/rmf-app/rmf-app.tsx
- packages/dashboard/src/components/schedule-visualizer/tests/robots-overlay.test.tsx
Signed-off-by: Teo Koon Peng <koonpeng@openrobotics.org>
> dashboard: temp fix for RMF api breakage

- example-deployment/k8s/fluentd-configmap.yaml
- packages/react-components/lib/reports/log-management/custom-lookup-filter.tsx
- packages/react-components/lib/reports/log-management/log-table.tsx
- packages/react-components/stories/logging.stories.tsx
- packages/react-components/tests/reports/log-management/log-management.spec.tsx
- packages/react-components/tests/reports/log-management/log-table.spec.tsx
- packages/reporting-server/models/raw_log.py
- packages/reporting-server/parsers/lift_state_parser.py
- packages/reporting-server/parsers/log_type_parser.py
- packages/reporting-server/parsers/test_log_type_parser.py
- packages/reporting-server/rest_server/app.py
- packages/reporting-server/rest_server/repositories/log_creation_handler.py
- packages/reporting-server/rest_server/repositories/report/__init__.py
- packages/reporting-server/rest_server/repositories/report/raw_log.py
- packages/reporting-server/rest_server/repositories/report/test_raw_log.py
- packages/reporting-server/rest_server/repositories/test_log_creation_handler.py
- packages/reporting-server/rest_server/routers/report.py
- packages/reporting/src/components/reports/all-logs-report.tsx
- packages/reporting/src/stories/reports/reporter-side-bar.stories.tsx
* Added a endpoint to filter logs by containers 
* Containers are dynamically added because the data can be pruned at some point (7 days)
* Added kubernetes information to logs
* Fix to postgres  parallel writing on new database (FUP PR add a migration lib to handle db change)
> reporting: Added more information to the rawlogs report

- packages/dashboard/e2e/tests/tasks.test.ts
- packages/dashboard/e2e/wdio.conf.js
> test: retry submit task test

- example-deployment/deploy.sh
Added configmap file of the reporting-server with a command on the deploy script.
> example-deployment:Fixed reporting-server not running with the deploy script

- example-deployment/keycloak-tools/bootstrap-keycloak.js
pre-requisite https://github.com/open-rmf/rmf-web/pull/357
Set reporting client scope and assigned that scope to the client. This fixed the reporting-server authentication issue on the kubernetes cluster.
> example-deployment:Fixed reporting auth uid problem

- packages/dashboard/scripts/setup/setup.js
Fixed get icons script and added get icons by workspace
> dashboard: fixed get icons script and added get icons by workspace

- packages/react-components/lib/tasks/task-panel.tsx
- packages/react-components/tests/tasks/task-panel.spec.tsx
> dashboard: reset create task form on close

- packages/dashboard/package.json
- packages/dashboard/rmf-launcher.ts
- packages/dashboard/src/components/rmf-app/contexts.ts
- packages/dashboard/src/components/rmf-app/index.tsx
- packages/dashboard/src/components/rmf-app/place.ts
- packages/dashboard/src/components/rmf-app/rmf-app.tsx
- packages/dashboard/src/components/rmf-app/utils.ts
- packages/dashboard/src/components/schedule-visualizer/tests/waypoints-overlay.test.tsx
- packages/dashboard/src/components/schedule-visualizer/waypoints-overlay.tsx
fixes #373
Waypoints now use the `PlacesContext` which should contain data from all nav graphs.
> fix(dashboard): fix missing waypoints

- packages/dashboard/src/components/tasks/task-page.tsx
- packages/react-components/lib/tasks/task-panel.tsx
- increase task rows from 10 to 20
- shift cancelled task to the back
> more rows and sort cancelled task

- packages/react-components/lib/robots/robot-table.tsx
- packages/react-components/lib/tasks/task-phases.tsx
- packages/react-components/lib/tasks/task-table.tsx
Added a shadow between each table row for demarcation and fixed the padding of the phase component in the task tab so that it is centralised
> minor changes to task and robot tabs

- packages/react-components/lib/form-inputs.tsx
- packages/react-components/lib/index.ts
- packages/react-components/lib/tasks/create-task.tsx
- packages/react-components/tests/form-inputs.spec.tsx
- packages/react-components/tests/tasks/create-task.spec.tsx
> fix(dashboard): only allow priority and number of loops to be >= 0

- packages/dashboard/src/managers/resource-manager-dispensers.ts
- packages/dashboard/src/managers/resource-manager-logos.ts
- packages/dashboard/src/managers/resource-manager-robots.ts
- packages/dashboard/src/managers/resource-manager.ts
> Cherrypick/ Dashboard: Fix dashboard does not get icons from kubernetes cluster

- Pipfile.lock
- packages/api-server/api_server/routes/test_fixtures.py
- packages/api-server/setup.py
- packages/reporting-server/setup.py
> chore: update deps, fix security issues

- example-deployment/README.md
- example-deployment/deploy.sh
- example-deployment/k8s/cronjobs.yaml
- packages/reporting-server/rest_server/app_config.py
- packages/reporting-server/rest_server/clean_logs.py
- packages/reporting-server/rest_server/default_config.py
- packages/reporting-server/setup.py
fixes #399 
Created script to delete logs from database > 7 days. This script is built into the application.
To run it you need to activate the virtual environment and run `reporting_server_clean_logs`.
> reporting-server:Created script and cronjob to delete logs from database > 7 days

- packages/reporting-server/README.md
Added documentation on the reporting-server
Hi @vallq , can you give me a hand here and provide me some doubts that you had, to write it down here. Some blockers should work too, we can create a FAQ.
> docs:reporting-server: Update reporting-server documentation

- packages/dashboard/src/components/schedule-visualizer/index.tsx
Signed-off-by: Teo Koon Peng <koonpeng@openrobotics.org>
> fix(dashboard): Robot trajectories continue to be polled even when map is unmounted #411

- example-deployment/deploy.sh
- packages/api-client/package.json
- packages/dashboard/src/components/rmf-app/rmf-app.tsx
- packages/dashboard/src/components/rmf-app/rmf-ingress.ts
> fix(dashboard): 401 Errors on prolonged rmf-web dashboard usage #398

- packages/react-components/lib/form-inputs.tsx
- packages/react-components/lib/tasks/create-task.tsx
> fix: Incorrect preview of batch tasks #421

- packages/reporting-server/rest_server/repositories/log_creation_handler.py
Removed payload from RawLog.create
> Fixed RawLog creation error

- packages/dashboard-e2e/tests/negotiations.test.ts
- packages/dashboard/src/components/dashboard/main-menu.tsx
- packages/dashboard/src/components/schedule-visualizer/robots-overlay.tsx
- packages/react-components/lib/benchmarks/robots.stories.tsx
- packages/react-components/lib/doors/door-marker.tsx
- packages/react-components/lib/form-inputs.tsx
- packages/react-components/lib/robots/base-marker.ts
- packages/react-components/lib/robots/default-marker.spec.tsx
- packages/react-components/lib/robots/robot-marker.spec.tsx
- packages/react-components/lib/robots/robot-marker.tsx
- packages/react-components/lib/robots/robot-markers.stories.tsx
- packages/react-components/lib/tasks/create-task.tsx
(cherry picked from commit 8eeda1b1a4532e9f937e9584609c9d59ba4745ba)
- Tooltip helper text under `priority` field in create task form
- Toolip with name and state over robots and doors icons 
- Lifts, Dispensers and Negotiations inactive in omnipanel main menu
- Fix some e2e test and unit test as a result of these changes
> tooltips and disable buttons

- example-deployment/rmf_server_config.py
There is a problem deploying the `rmf-server` with the current version of the main. This change fixes this.
```
Traceback (most recent call last):
File "/usr/local/bin/rmf_api_server", line 5, in <module>
from api_server.__main__ import main
File "/usr/local/lib/python3.8/dist-packages/api_server/__main__.py", line 3, in <module>
from .app import app
File "/usr/local/lib/python3.8/dist-packages/api_server/app.py", line 17, in <module>
from .app_config import AppConfig, default_config
File "/usr/local/lib/python3.8/dist-packages/api_server/app_config.py", line 41, in <module>
default_config = load_config(default_config_file)
File "/usr/local/lib/python3.8/dist-packages/api_server/app_config.py", line 30, in load_config
config = …
```
> FIX: Changed the rmf config structure of the dict

- packages/dashboard/src/components/schedule-visualizer/index.tsx
Fix for zooming in when navigating out and back to the building map.
> make sure lmap gets set on re render

- packages/dashboard-e2e/tests/ui-interactions.test.ts
- packages/react-components/lib/robots/robot-marker.tsx
Extend svg `textWidth` from 3 to 8. It is enough to fit the length of the corridor where robots are in the map. Hopefully, it will be enough to accommodate robot names in all sorts of devices. Also made some changes to the positioning of the text field.
> increase svg text size

- packages/dashboard/src/app-config.ts
- packages/dashboard/src/managers/resource-manager-dispensers.ts
- packages/dashboard/src/managers/resource-manager-logos.ts
- packages/dashboard/src/managers/resource-manager-robots.ts
- packages/dashboard/src/managers/resource-manager.ts
- packages/dashboard/src/managers/tests/resource-manager.test.tsx
Also added some debug outputs to resource loading.
> fix(dashboard): default logo not used when headerLogo is not provided

- packages/dashboard-e2e/tests/ui-interactions/submit-task.test.ts
- packages/dashboard-e2e/wdio.conf.js
Signed-off-by: Teo Koon Peng <koonpeng@openrobotics.org>
> test(dashboard-e2e): fix safari

- packages/api-server/api_server/routes/lifts.py
- packages/dashboard/src/components/dashboard/dashboard.tsx
- packages/react-components/lib/doors/door-panel.tsx
- packages/react-components/lib/doors/door-table.tsx
- packages/react-components/lib/lifts/lift-panel.tsx
- packages/react-components/lib/lifts/lift-table.tsx
- packages/react-components/lib/lifts/lift-utils.ts
- packages/react-components/lib/workcells/workcell-panel.tsx
- packages/react-components/lib/workcells/workcell-table.tsx
New building map panel is unusable in larger maps (e.g. clinic) due to large number of entities. This workaround it by rendering at a fixed rate as opposed to whenever new data is available, rendering of each cell/row is also improved by the use of memos.
This is not an ideal solution, for the long term, we should use virtualized table/lists. Also this does not address the design issues when there are lots of entities.
> perf: dashboard

- .github/pull_request_template.md
* Added new self-check line for prototyping on Figma
> Added self check for prototyping on Figma

- packages/dashboard/rmf-launcher.js
Signed-off-by: Elias De Coninck <elias@tractonomy.com>
Additional environment variable called `RMF_DASHBOARD_DEMO_PACKAGE` to load a map from a different package than `rmf_demos_gz`.
> dashboard: support custom gazebo launch package

- Pipfile
- Pipfile.lock
- packages/api-server/pyproject.toml
- packages/reporting-server/pyproject.toml
- packages/ros-translator/pyproject.toml
updating black and removing pyproject.toml seems to fix the issue
> build: fix pipenv install

- scripts/bootstrap.sh
> ci: workaround npm install bug

- package-lock.json
> deps: npm audit fix

- .github/workflows/api-server.yml
- .github/workflows/dashboard.yml
- .github/workflows/react-components.yml
- .github/workflows/reporting-server.yml
- .github/workflows/reporting.yml
- .github/workflows/rmf-auth.yml
- .github/workflows/ros-translator.yml
> ci: run linter on react-components

- .github/workflows/api-client.yml
- .github/workflows/rmf-auth.yml
- package-lock.json
- package.json
- packages/api-client/package.json
- packages/react-components/package.json
- packages/rmf-auth/package.json
> ci: do not allow eslint warnings

- package-lock.json
- packages/api-server/api_server/app.py
Signed-off-by: Teo Koon Peng <koonpeng@openrobotics.org>
> fix(api-server): fix some routes not requiring authentication

- .github/workflows/api-client.yml
- .github/workflows/api-server.yml
- .github/workflows/dashboard-e2e.yml
- .github/workflows/dashboard.yml
- .github/workflows/nightly.yml
- .github/workflows/react-components.yml
- .github/workflows/reporting-e2e.yml
- .github/workflows/reporting-server.yml
- .github/workflows/reporting.yml
- .github/workflows/rmf-auth.yml
- .github/workflows/ros-translator.yml
> CI: use matrix to test with older npm ver

- .github/workflows/api-client.yml
- .github/workflows/api-server.yml
- .github/workflows/dashboard-e2e.yml
- .github/workflows/dashboard.yml
- .github/workflows/nightly.yml
- .github/workflows/react-components.yml
- .github/workflows/reporting-e2e.yml
- .github/workflows/reporting-server.yml
- .github/workflows/reporting.yml
- .github/workflows/rmf-auth.yml
- .github/workflows/ros-translator.yml
The npm script bug has been fixed so we can remove the alternative matrix now.
Fixes #559.
> ci: remove npm 8.5.3

- Pipfile
- Pipfile.lock
- packages/ros-translator/ros_translator/typescript/test/test.sh
- packages/ros-translator/setup.py
Fixes broken test in `ros-translator`, due to https://github.com/microsoft/TypeScript/issues/8186.
> Fix ros-translator CI test

- packages/api-server/api_server/authenticator.py
- packages/api-server/api_server/gateway.py
- packages/api-server/api_server/query.py
- packages/api-server/api_server/repositories/static_files.py
- packages/api-server/api_server/rmf_io/book_keeper.py
- packages/api-server/api_server/rmf_io/health_watchdog.py
- packages/api-server/api_server/test/test_client.py
- packages/dashboard/src/components/app.tsx
> fix: fixes from upgrading deps

- packages/react-components/lib/tasks/create-task.tsx
One-liner change to fix lint CI
https://github.com/open-rmf/rmf-web/pull/622#issuecomment-1170721303
> fix lint by remove unnecessary mui import

- packages/dashboard/src/components/map-app.tsx
Fixes https://github.com/open-rmf/rmf-web/issues/640, and partially fixes https://github.com/open-rmf/rmf-web/issues/532
Left to do,
* fix transformation when floors are toggled. This can be seen from the misalignment of the lifts.
https://user-images.githubusercontent.com/5383623/192833222-4c094381-4ebc-4c9e-9a10-46bc7b0b8ce5.mp4
* robot icon requires refreshing the dashboard to show up on a different level
https://user-images.githubusercontent.com/5383623/192837405-a450e173-6845-4641-8f86-39ca1eedc320.mp4
> Fixing level changing behavior

- packages/api-server/README.md
- packages/api-server/api_server/__main__.py
- packages/api-server/api_server/app_config.py
- packages/api-server/api_server/models/tortoise_models/tasks.py
- packages/api-server/api_server/repositories/tasks.py
- packages/dashboard/src/components/tasks/tasks-app.tsx
- packages/react-components/lib/tasks/task-table-datagrid.tsx
Continuation of https://github.com/open-rmf/rmf-web/pull/651, implementing server-side sorting.
Incorporates changes from https://github.com/open-rmf/rmf-web/pull/538, since database migration will be required.
https://user-images.githubusercontent.com/5383623/203946045-035ad1e4-8c31-46df-bb8b-e8b3fecfdca5.mp4
> Server-side sorting

- packages/api-server/api_server/dependencies.py
- packages/dashboard/src/components/tasks/tasks-app.tsx
- packages/react-components/lib/tasks/task-table-datagrid.tsx
* Export full task history to CSV file.
https://user-images.githubusercontent.com/5383623/208853689-239d9f66-adff-44e6-9f1e-36cc547980d4.mp4
* Added `columns`, `density` and `filter` selectors to the toolbar as well.
* make filtering reactive as input is being written, instead of only being applied after preference panel is closed.
> Basic export of all tasks in the database

- .github/workflows/nightly.yml
- .github/workflows/ros-translator.yml
* fix e2e image building from `nightly`
* Use e2e images for `ros-translator` workflow
> Using e2e docker image to run translator test

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- packages/api-server/README.md
- packages/dashboard/README.md
- packages/dashboard/package.json
- packages/dashboard/src/components/appbar.tsx
- packages/react-components/lib/header-bar.spec.tsx
- packages/react-components/lib/header-bar.stories.tsx
* Made README more :sparkles: 
* Updated and consolidated documentation, removed stale documentation
* Made dashboard building command build prerequisites too
* Changed OpenRMF to Open-RMF
* Added link to https://github.com/open-rmf/rmf-web/pull/704
> Documentation

- packages/dashboard/src/components/map-app.tsx
- Click map icon for robot state overlay
[chrome-capture-2023-4-19.webm](https://github.com/open-rmf/rmf-web/assets/37310205/d11245a7-2929-4aa8-b4af-bae3b95cb61e)
> Show Robot summary after clic robot icon

- packages/dashboard/src/components/app-events.ts
- packages/dashboard/src/components/map-app.tsx
- Map persistence, for handling looking at parts of a large map, navigating away and back to the map tab
- Map label persistence
- This PR does not add zoom by default per map. 
[chrome-capture-2023-4-25.webm](https://github.com/open-rmf/rmf-web/assets/37310205/4581a444-eece-4c92-9e5b-539f9e347e50)
> Map persistence

- packages/dashboard/src/components/lifts-app.tsx
- packages/react-components/lib/lifts/lift-table-datagrid.tsx
- packages/react-components/lib/lifts/lift-utils.ts
> Op. Mode column in Lifts

- packages/dashboard/src/components/doors-app.tsx
- packages/react-components/lib/doors/door-table-datagrid.tsx
- packages/react-components/lib/doors/utils.ts
> Op. Mode column in Door

- packages/dashboard/src/components/appbar.tsx
- packages/dashboard/src/managers/resource-manager.ts
- Question mark button was added
- Default leads to https://osrf.github.io/ros2multirobotbook/rmf-core.html
- Configurable in dashboard resources
- If configured in dashboard resources, leads to that URL
- Exclamation mark button was added
- Default leads to https://github.com/open-rmf/rmf-web/issues
- Configurable in dashboard resources
- If configured in dashboard resources, leads to that URL
[chrome-capture-2023-5-7.webm](https://github.com/open-rmf/rmf-web/assets/37310205/8010e805-89b1-4427-bb5f-ac3782c49e94)
> Help and report issues buttons 

- .github/actions/bootstrap/action.yml
Run CI with older pnpm till https://github.com/pnpm/pnpm/issues/6994 is fixed.
> Fix pnpm version till #6994 is fixed

- packages/dashboard/src/components/appbar.tsx
* Remove constraint for non-zero length pickup and dropoff handlers. Since we are not using the traditional delivery, and RMF does not need those fields to request from a dispenser or ingestor.
> Remove constraint for non-zero length pickup and dropoff handlers

- packages/dashboard/src/components/app-base.tsx
- packages/react-components/lib/alert-dialog.tsx
* Use `Ctrl-Minus`
* Do not display acknowledge button if the alert has not been acknowledged and no callback is provided
> Fixes prompt text, do not display ack button if not awknowledged and no callback

- packages/dashboard/src/components/tasks/task-schedule-utils.ts
- packages/react-components/lib/tasks/create-task.tsx
- Add more description to the event title
> Schedule event title

- packages/dashboard/src/components/tasks/task-schedule-utils.ts
- packages/react-components/lib/tasks/create-task.tsx
* Add rounds and join places in the short description function
* Add [] between places
---------
(cherry picked from commit c1d78d2ee6999161db8852df0216433ec8c1cbe8)
> Schedule event title (#782)

- packages/api-server/api_server/routes/tasks/scheduled_tasks.py
- packages/dashboard/src/components/tasks/task-schedule-utils.ts
- packages/dashboard/src/components/tasks/task-schedule.tsx
> Fix - schedule single event

- packages/react-components/lib/lifts/lift-request-dialog.tsx
* Detect 0 as number as well
* Display error when fields are left empty during submit
---------
(cherry picked from commit 99ecd3126d3e29d6ad9d8e21d880eadb1d8efc43)
> Detect 0 as number as well (#793)

- packages/dashboard/src/components/app-events.ts
- packages/dashboard/src/components/three-fiber/camera-control.tsx
[chrome-capture-2023-9-12 (1).webm](https://github.com/open-rmf/rmf-web/assets/37310205/761e187f-1173-4e4c-a6e2-0e4f81eb5c22)
> Retain camera position after changing tabs

- packages/dashboard/src/components/three-fiber/camera-control.tsx
* Use gl element instead of window element
* Remove console log
---------
(cherry picked from commit f722d649bd71995f9aa64fc66a8d85ed5569deb6)
> Fix wheel behavior  (#805)

- packages/react-components/lib/tasks/create-task.tsx
Temporarily bring back patrol task.
> Basic workaround support for patrol-task

- packages/react-components/lib/map/three-fiber/robot-three-maker.tsx
(cherry picked from commit 59065b15e7e3221b45ef4f99de5f5ba75401c9c1)
Port map font fix.
> Fix oddly failing robot label and use same as other labels (#812)

- packages/dashboard/src/components/three-fiber/lift-three.tsx
- packages/dashboard/src/components/three-fiber/robot-three.tsx
> Using public URL to access font

- packages/dashboard/src/components/three-fiber/layer-control.test.tsx
- packages/dashboard/src/components/three-fiber/layers-controller.tsx
- packages/react-components/lib/map/three-fiber/circle-shape.spec.tsx
- packages/react-components/lib/map/three-fiber/circle-shape.tsx
- packages/react-components/lib/map/three-fiber/cube-marker.spec.tsx
- packages/react-components/lib/map/three-fiber/index.tsx
- packages/react-components/lib/map/three-fiber/robot-three-maker.spec.tsx
- packages/react-components/lib/map/three-fiber/robot-three-maker.tsx
- packages/react-components/lib/map/three-fiber/shape-three-rendering.spec.tsx
- packages/react-components/lib/map/three-fiber/shape-three-rendering.tsx
- packages/react-components/lib/map/three-fiber/text-maker.spec.tsx
- packages/react-components/package.json
- pnpm-lock.yaml
- Test added for react three fiber components
> Test for react three fiber component

- packages/dashboard/src/components/map-app.tsx
- packages/dashboard/src/components/three-fiber/robot-three.tsx
Safer access to maps and records before rendering robots.
> Check if robot location is available before attempting to render

- packages/dashboard/src/components/map-app.tsx
- packages/dashboard/src/components/three-fiber/robot-three.tsx
- Fix the problem that the robot kept appearing on the wrong floor after going up with the elevator to the next floor. 
[chrome-capture-2023-10-2.webm](https://github.com/open-rmf/rmf-web/assets/37310205/249753d5-6920-4d1c-af8c-5df9f88ce63a)
[chrome-capture-2023-10-2 (1).webm](https://github.com/open-rmf/rmf-web/assets/37310205/5f757103-eda6-468c-94b5-5d8e32c2bfa2)
> Display robot according to its level correctly 

- packages/dashboard/src/components/map-app.tsx
Fix call depth issue from updating level of robots.
> Fix recursive call in effect

- packages/dashboard/src/components/three-fiber/lift-three.tsx
- packages/dashboard/src/components/three-fiber/robot-three.tsx
- Fix the infinite call in font search
> Add dependency to useEffect to avoid rerenders

- packages/api-client/lib/openapi/api.ts
- packages/api-client/lib/version.ts
- packages/api-client/schema/index.ts
- packages/api-server/api_server/models/delivery_alerts.py
- packages/api-server/api_server/rmf_io/book_keeper.py
- packages/api-server/api_server/routes/delivery_alerts.py
- packages/dashboard/src/components/delivery-alert-store.tsx
- Field filters are added
- A new endpoint is created
[chrome-capture-2023-10-10.webm](https://github.com/open-rmf/rmf-web/assets/37310205/217440aa-4dce-4ef2-b4ba-53a2c042e2f2)
> Add query filter for delivery alerts

- packages/dashboard/src/components/app-events.ts
- packages/dashboard/src/components/app.tsx
- packages/dashboard/src/components/map-app.tsx
- packages/dashboard/src/managers/resource-manager.ts
* new app event to check if a user just logged in
* configurable default level to display when user just logged in
> New app event specifically for checking just logged in to tweak the default map

- packages/dashboard/src/components/appbar.tsx
- packages/dashboard/src/components/robots/robots-workspace.tsx
- packages/dashboard/src/components/tasks/tasks-app.tsx
- packages/dashboard/src/components/three-fiber/layers-controller.tsx
- packages/react-components/lib/beacons/beacon-table-datagrid.tsx
- packages/react-components/lib/doors/door-table-datagrid.tsx
- packages/react-components/lib/lifts/lift-table-datagrid.tsx
- packages/react-components/lib/robots/robot-table-datagrid.tsx
- packages/react-components/lib/tasks/task-table-datagrid.tsx
- packages/react-components/lib/window/window-toolbar.tsx
- Make appbar font and size smaller
- Smaller map buttons
- Smaller data grid
[chrome-capture-2023-10-20.webm](https://github.com/open-rmf/rmf-web/assets/37310205/83d52f79-1fb9-429d-904e-cd0bf2d323df)
> Adjustments for screen heights less than 800

- packages/dashboard/src/components/tasks/tasks-app.tsx
* clicking on task centers on the robot that was assigned
> Clicking on task centers on robot

- packages/dashboard/src/components/door-summary.tsx
- packages/dashboard/src/components/lift-door-summary.tsx
- packages/dashboard/src/components/lift-summary.tsx
- packages/dashboard/src/components/map-app.tsx
- packages/dashboard/src/components/three-fiber/door-three.tsx
- packages/dashboard/src/components/three-fiber/lift-three.tsx
- packages/react-components/lib/map/three-fiber/cube-maker.tsx
- packages/react-components/lib/map/three-fiber/door-three-maker.tsx
- packages/react-components/lib/map/three-fiber/lift-three-maker.tsx
- Door summary
- Lift summary
[chrome-capture-2023-10-28.webm](https://github.com/open-rmf/rmf-web/assets/37310205/dd4018cd-bb40-47d2-a658-01cf66323bd6)
> Door and lift summary

- packages/dashboard/src/components/map-app.tsx
- packages/react-components/lib/robots/robot-table-datagrid.tsx
* clip battery decimal values
* filter trajectories for irregular segments at the start
> Minor frontend fixes

- packages/dashboard/src/components/delivery-alert-store.tsx
- Adjust content according to screen size
> Delivery dialog - Adapting styles according to resolution 

- packages/api-server/api_server/rmf_io/book_keeper.py
- packages/api-server/api_server/routes/internal.py
- packages/rmf-auth/lib/keycloak.ts
* monitors disconnections of websocket on `_internal` route
* shuts down server if more than 5 disconnections happen within 2 minutes
* clean up keycloak authenticator console logging
> Shuts down server if websocket connection is unhealthy

- packages/api-server/api_server/routes/tasks/scheduled_tasks.py
Quick fix (untested) for `except_date` being applied to the wrong day. I am working on a more robust fix that address some of the problem with the way `except_date` is currently handled, but that would require some extra changes to make it possible to unittest schedules so we should probably wait till the branch gets merged to `main`.
> except date quickfix

- packages/dashboard/src/components/robots/robots-app.tsx
* Reduces the number of queries made by the robot app, only refreshes at intervals of 10 seconds instead of by subscription 
This should further reduce the queries made between the dashboard and the api-server
> Query for fleets and tasks only once every 10 seconds

- packages/dashboard/src/components/permissions.ts
Allow all users to cancel tasks for now.
> Allow all users to cancel tasks for now

- .github/workflows/ghpages.yml
- packages/api-server/api_server/app.py
- packages/api-server/package.json
- packages/api-server/scripts/docs_config.py
- packages/api-server/scripts/extract_docs.py
Fix the broken docs after we switched to serving swagger ui locally. Also fix the root path when serving the docs, now we don't have to hack index.html anymore.
https://open-rmf.github.io/rmf-web/
> api-server: fix docs page

- packages/dashboard/src/components/lift-summary.tsx
> Remap session ID label from sessionId to Session ID

- .github/workflows/ghpages.yml
- packages/api-server/scripts/docs_config.py
- packages/api-server/scripts/extract_docs.py
> api-server: fix ghpages

- packages/api-server/api_server/gateway.py
Increasing queue size for doors and beacons
> Increase queue for beacon and doors

- packages/api-client/package.json
- packages/api-server/package.json
- packages/api-server/setup.py
- packages/dashboard-e2e/package.json
- packages/dashboard/package.json
- packages/react-components/package.json
- packages/rmf-auth/package.json
- packages/rmf-models/package.json
- packages/ros-translator/package.json
- packages/ros-translator/ros_translator/test/ros_translator_test_msgs/package.xml
- packages/ros-translator/setup.py
- pipenv-install/package.json
* Bump versions
* Added descriptions where necessary
> Bump versions to 0.1.0

- packages/api-client/lib/index.spec.ts
- packages/api-client/lib/index.ts
> Fix linting on api-client

- packages/api-client/package.json
- packages/dashboard/package.json
- pnpm-lock.yaml
Updates `axios` to `1.7.4` to resolve severity report
> Update axios to 1.7.4

- packages/react-components/lib/tasks/create-task.tsx
- packages/react-components/lib/tasks/task-table-datagrid.tsx
- packages/react-components/lib/tasks/utils.ts
* Made task form a little nicer
* Changed location of favorite task button, added icon
* Changed warning time toggle to use a switch (checkboxes were not as appropriate)
* Added binary priority selection (requires https://github.com/open-rmf/rmf_ros2/pull/381)
* Prioritzed tasks will have a Bolt icon beside the user/scheduled icon
* Fix workaround and use labels to indicate if a task was scheduled (instead of using `username__scheduled`)
* Removed unused starting time field
before review:
https://github.com/user-attachments/assets/4cd46a88-a298-486f-b696-7ec3d825f4eb
after review UI changes:
> Task prioritization and cleanup of task form

- README.md
Documenting the fix mentioned in https://github.com/open-rmf/rmf-web/issues/1005 as a troubleshooting step.
> Add troubleshooting step for levels not rendering

- .github/workflows/nightly.yml
- README.md
* `rolling` and `jazzy` for `minimal-rmf`
* `rolling` and `jazzy` for `api-server`
* `latest` for dashboard
* update README
Matrix build for `rolling` and `jazzy` for all images
> Setting up matrix for rolling and jazzy

- packages/dashboard/.gitignore
- packages/dashboard/examples/keycloak/README.md
- packages/dashboard/examples/keycloak/api_server_config.py
- packages/dashboard/examples/keycloak/index.html
- packages/dashboard/examples/keycloak/index.tsx
- packages/dashboard/examples/keycloak/keycloak-setup.bash
- packages/dashboard/examples/keycloak/utils.bash
- packages/dashboard/src/components/rmf-dashboard.tsx
- packages/dashboard/src/services/keycloak.ts
- packages/dashboard/src/services/rmf-api.ts
Preliminary fix for the dashboard not redirecting to login page. I tested using a local keycloak instance, will add instructions to run with keycloak later.
> dashboard: fix not redirecting to login

- packages/api-client/package.json
- packages/api-server/package.json
- packages/api-server/setup.py
- packages/dashboard/package.json
- packages/react-components/package.json
- packages/rmf-models/package.json
- packages/ros-translator/package.json
- packages/ros-translator/ros_translator/test/ros_translator_test_msgs/package.xml
- packages/ros-translator/setup.py
- pipenv-install/package.json
Bumping to version 0.2.0 to prepare for a release.
> Bump to version 0.2.0

- .github/demo-dashboard/Dockerfile
- packages/rmf-dashboard-framework/package.json
- pnpm-lock.yaml
It is no longer maintained and does not have binaries for the latest lts anymore. Fixes #1023
> [rmf-dashboard-framework] remove canvas

- .github/workflows/nightly.yml
> Fix nightly images
