open-rmf/rmf-web

package-lock.json, package.json, src/components/schedule-visualizer/door/door-double-hinge.tsx, src/components/schedule-visualizer/door/door-double-slide.tsx, src/components/schedule-visualizer/lift.tsx, src/e2e-tests/soss.yaml, src/util/angle-calculation.ts
Fixes #28 
Updated `romi-js-core-interfaces` to **"0.0.2-alpha.7"** and added `dispenser_states` on soss config
=> Fix for dashboard does not start after PR#21

src/components/schedule-visualizer/door/tests/door.test.tsx, src/components/schedule-visualizer/tests/arrow.test.tsx, src/components/schedule-visualizer/tests/lift.test.tsx, src/components/schedule-visualizer/tests/place.test.tsx, src/components/schedule-visualizer/tests/robot-trajectory.test.tsx, src/components/schedule-visualizer/tests/robot.test.tsx, src/components/tests/app.test.tsx, src/components/tests/dispenser-item.test.tsx, src/components/tests/dispensers-panel.test.tsx, src/components/tests/door-item.test.tsx, src/components/tests/doors-panel.test.tsx, src/components/tests/lift-item.test.tsx, src/components/tests/lifts-panel.test.tsx, src/components/tests/main-menu.test.tsx, src/components/tests/places-panel.test.tsx, src/components/tests/robots-panel.test.tsx
Requires #20 to be merged first.
Fixes #22
Move tests files of the `components` folder to `components/tests/ ` and tests of `/components/schedule-visualizer`/ to `/components/schedule-visualizer/tests/`
=> Tests files moved to tests folders

src/components/schedule-visualizer/lift.tsx, src/components/schedule-visualizer/tests/lift.test.tsx
Fixes #30 
* We now use dark grey when the lift is not initialized.
* If the mode of the lift is `UNKNOWN` and if the lift has defined states, the current_level will be shown instead of the `UNKNOWN` label.
* When the lift is stationary at a level, the printout is the current_level name but if the lift is moving, it prints the destination text (L1->L3) at the same location.
* Switched places of the LiftMotion text and LiftMode text
=> Improved lift UX #30

README.md, package.json, src/app-config.ts, src/react-app-env.d.ts
=> fix: use env vars to specify soss and trajectory server urls

src/components/schedule-visualizer/trajectory-animations.tsx
Fixes #41 
Fixed the outline trajectory both in Chrome and Firefox
The problem was that the trajectory mask did not cover the entire trajectory space. I solved the problem by giving more space to the mask.
=> Fix/outline trajectory animation sometimes clips#41

.storybook/main.js, package-lock.json, package.json, src/stories/0-Welcome.stories.js
* Added storybook
* Updated Typescript version
* Added storybook script
We added something call Storybook to the project. The storybook is a user interface, software development environment, and playground for UI components. The main purpose of it is to allow you to create components independently in an isolated development environment outside the main application. We can also use this to show our components in their different states.
Storybook runs on its own web server and provides a catalog view for the components for our application. We can run the storybook project with `npm run-script storybook` command.
Using the Storybook will also force us to split the component into two: (1) presentational components (the component with no logic behind); and (2) container components (where the …
=> Add storybook to romi-dashboard

src/components/loop-form.tsx
On the commands panel, selecting an empty fleet (when you click the cancel option inside the autocomplete for target fleet) will result in the error thrown above, crashing the app. This is because the value of the fleet is not in the places object, hence `setListOfPlaces` would set the `listOfPlaces` value as `undefined. 
I added a simple check to make sure that the value of the fleet is in the places object, otherwise, the value would be set to an empty array.
=> fix unknown target fleet form errors

package-lock.json, src/components/schedule-visualizer/robot-default-icon.tsx, src/components/schedule-visualizer/robot-image-icon.tsx, src/components/schedule-visualizer/robot.tsx
In storybook, clicking on the robot icons triggers 2 onclick callback.
This was previously fixed but seems to have came back.
=> fix: robot double click regression

src/components/schedule-visualizer/robot-default-icon.tsx, src/components/schedule-visualizer/robot-image-icon.tsx, src/components/schedule-visualizer/robot.tsx
This is built on top of #92.
For some reason the subelements of a robot icon like text, direction line etc are select-able in storybook, but it's not select-able in the dashboard. This do some refactoring to handle all events in the generic "robot icon" container so the storybook icons works the same way as the dashboard.
=> fix: robot icon subelements selectable

src/components/schedule-visualizer/robot-default-icon.tsx
This is built on top of #94.
This fixes a bug where shadows are missing when the robot name has spaces, this is caused by unescaped filter ids in the elements.
=> fix: missing shadows for robot names with spaces

.github/workflows/nightly.yml, README.md, docker/chrome-no-sandbox, docker/docker-compose.yml, docker/e2e.Dockerfile, e2e/env.sh, e2e/rmf-launcher.ts, package-lock.json, package.json, wdio.conf.js
Currently, the CI is ran by launch rmf services in a docker container and wdio/chrome on the host. The creates a problem that makes it hard for the CI to depend on rmf_demos for resource pack that is mandatory for dispensers to work. It may also makes it less stable as the why the tests are ran is different from what developers would use.
This change runs the whole CI in docker "natively", an e2e image is built nightly, this repo is then mounted onto that image and the tests are ran as if all the services are on the local host, hopefully this will make it easier to import resource pack when building the CI.
Relevant: #89
=> ci: run e2e natively

packages/dashboard/e2e/package.json, packages/dashboard/package.json
Fixes #135
Fixes the below error on `npm run  test:e2e:dev` execution:
```
sh: 1: wdio: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! romi-dashboard@0.0.1-alpha.0 test:e2e:dev: `cd e2e && . ./env.sh && ROMI_DASHBOARD_PORT=3000 ROMI_DASHBOARD_LAUNCH_MODE=none wdio`
npm ERR! spawn ENOENT
```
=> Fixed test:e2e:dev command

.github/pull_request_template.md
Hey guys, Tagging you all for awareness. =) 
fixes #146 
Added description to the `fixes` line. The idea is to place a GH issue (if exists of course) on fixes. E.g. when this PR is merged the issue #146 should be close automatically. If you don't have a related issue you can either remove that line or leave it blank.
Does not apply
Is that description ok?
=> Added description to the `fixes` line

packages/dashboard/scripts/setup/get-icons.js
fixes #148
* Using the `origin` name creates problems if people already have a local remote name defined as origin. Renamed remote repo from `origin` to `resources`
* Added a safeguard in case the tmp is in an inconsistent state.
Does not apply
=> Renamed the remote from `origin` to `resources`

.gitignore
I added a new file `npm-debug-log` to exclude in `.gitignore`.
This is to exclude committing the `npm-debug-log` that is generated when running operations from npm commands in `react-components`.
A line in the `.gitignore` file at the root folder to exclude `npm-debug.log`.
=> add npm debug log to .gitignore

packages/dashboard/e2e/tests/task-summary.test.ts, packages/dashboard/src/components/dashboard.tsx, packages/dashboard/src/components/main-menu.tsx, packages/dashboard/src/components/task-summary-panel-item.tsx, packages/dashboard/src/components/task-summary-panel.tsx, packages/dashboard/src/components/tests/__snapshots__/task-summary-panel-item.test.tsx.snap, packages/dashboard/src/components/tests/__snapshots__/task-summary-panel.test.tsx.snap, packages/dashboard/src/components/tests/__snapshots__/tree-button-group.test.tsx.snap, packages/dashboard/src/components/tests/task-summary-panel-item.test.tsx, packages/dashboard/src/components/tests/task-summary-panel.test.tsx, packages/dashboard/src/components/tests/tree-button-group.test.tsx, packages/dashboard/src/components/tree-button-group.tsx, packages/dashboard/src/managers/task-manager.ts, packages/dashboard/src/managers/tests/task-manager.test.ts, packages/dashboard/src/mock/data/task-summary.ts, packages/dashboard/src/mock/fake-transport.ts
pre-requisite https://github.com/osrf/romi-dashboard/pull/153 [Merged]
fixes #
* Created a taskSummary windows on the omnipannel with a tree structure, 
* Subscribed to TaskSummary
* Created mock
* Added a pause button but it is not implemented yet.
* Add unit tests
* Add e2e tests
If we will keep the tree button group component I'll refactor the negotiation panel in another PR
=> Check tasks (plans) on the Dashboard

.github/workflows/nightly.yml, .github/workflows/pull-requests.yml, packages/dashboard/docker/docker-compose.yml, packages/dashboard/docker/e2e.Dockerfile, packages/dashboard/docker/rmf/docker-compose.yml, packages/dashboard/e2e/README.md, packages/dashboard/package.json
Rename docker packages to `rmf-web` after name change from `romi-dashboard`
=> fix docker packages from name change

packages/dashboard/src/components/schedule-visualizer/lift-overlay.tsx, packages/dashboard/src/components/schedule-visualizer/tests/lifts-overlay.test.tsx, packages/react-components/lib/lifts/lift-marker.tsx
fixes #171
Added style picker according to state priority on lifts.
Should I add tests on the lift-overlay that checks the lift style "business logic"? or a test of the variant on the react-component it's enough? 
I think having both will be great. One to check the component's correct color assignation and the other one to pick the style in the correct order of priority.
=> Added style picker according to state priority on lifts

packages/ros2-bridge/package.json, packages/ros2-bridge/src/index.ts
A recent rclnodejs update change the SIGINT behavior to no longer forcefully exit the process, instead it just stops all contexts. The "problem" comes from the fact that because it installs a signal handler, the default nodejs handler no longer gets called so we need to install our own handler to close the server.
=> fix ros2-bridge not exiting on SIGINT

packages/dashboard/src/components/dashboard.tsx
This fixes a recent change that causes the omnipanel to show the doors panel by default instead of the main menu.
=> fix omnipanel not showing the main menu by default

packages/ros2-bridge/src/authenticator.ts
not quite sure exactly how it affects the middleware chainning. In theory, not returning may cause the authenticator to run checks on data that it is not meant to do.
=> ros2-bridge: return after the next() call

packages/react-components/.storybook/main.js
Since `prepare` builds the typescript files, storybook by default uses the js files instead of the ts, this caues hot reload to not work.
=> react-components: prefer ts in storybook

scripts/bootstrap.js
this is useful when switching branches or pulling new changes to ensure everything is up to date.
The old behavior is present because it used to be that we recursively install dependent packages, this is no longer the case, we now require the user to manually run bootstrap.
=> build: always run npm regardless if node_modules is present

packages/react-components/lib/task-summary/task-summary-accordion.tsx
Fixed the following problem between the typescript compiler and the typescript linter by using the tree type of material-ui library.
``` bash
../../node_modules/@material-ui/lab/TreeView/TreeView.d.ts:96:3
96   onNodeSelect?: (event: React.ChangeEvent<{}>, nodeIds: string) => void;
~~~~~~~~~~~~
The expected type comes from property 'onNodeSelect' which is declared here on type '(IntrinsicAttributes & SingleSelectTreeViewProps) | (IntrinsicAttributes & MultiSelectTreeViewProps)'
lib/task-summary/task-summary-accordion.tsx:128:7 - error TS2322: Type '(event: React.ChangeEvent<Record<string, unknown>>, nodeIds: string[]) => void' is not assignable to type '(event: ChangeEvent<{}>, nodeIds: string[]) => void'.
Types of parameters 'event' and 'event' are incompatible.
Type 'ChangeEvent<{}>' is …
```
=> Fixed type problem of tree event by adding tree library`s type

packages/dashboard/docker/docker-compose.yml, packages/dashboard/e2e/README.md, packages/dashboard/e2e/env.sh, packages/dashboard/e2e/scripts/auth-ready.js, packages/dashboard/e2e/scripts/test-e2e.js
dashboard: change keycloak port to avoid conflict
=> dashboard: change keycloak port to avoid conflict

packages/dashboard/src/components/dashboard/dashboard.tsx, packages/dashboard/src/components/schedule-visualizer/index.tsx
Signed-off-by: Morgan Quigley <morgan@osrfoundation.org>
The ScheduleVisualizer component now uses the fleet context directly, rather than receiving it via `props`. Then the parent component doesn't need to render every time the fleet context is updated. This is helpful for the mosaic layout manager (will come in a future PR, currently it's sitting in a branch).
=> dashboard: ScheduleVisualizer now uses the fleet context directly

packages/dashboard/src/components/dashboard/dashboard.tsx, packages/dashboard/src/components/schedule-visualizer/index.tsx
Signed-off-by: Morgan Quigley <morgan@osrfoundation.org>
Moves the trajectory manager context into the `ScheduleVisualizer` component, to continue factoring stuff out of `Dashboard` and into `ScheduleVisualizer` so that it's easier to re-use. Tested in simulation; the trajectory animations still work.
=> dashboard: refactor trajectory manager context into schedule visualizer

package.json, packages/api-server/pyproject.toml, scripts/pipenv-install.js
pipenv has a bug? where you get ".project" file not found when running with "--site-packages" multiple times, it also cleans up the existing venv, removing the .gitignore file.
=> build: fix error when running bootstrap multiple times

example-deployment/README.md, example-deployment/k8s/fluentd-configmap.yaml, example-deployment/k8s/fluentd.yaml, example-deployment/k8s/minio.yaml
Related to #281
* Updated Readme with installation instructions of Fluentd and Minio
* Created a Fluentd configmap file for Fluentd and a deploy file.
* Created a MinIO deploy file with an ingress on `example.com/minio`
* Fluentd collects all logs and sends those logs to MinIO where are stored in chunks of 5mb.
=> example-deployment:Add fluentd and MinIO to kubernetes cluster

packages/react-components/lib/reports/log-management/custom-lookup-filter.tsx, packages/react-components/lib/reports/log-management/log-table.tsx, packages/react-components/stories/logging.stories.tsx, packages/react-components/tests/reports/log-management/log-table.spec.tsx, packages/reporting-server/rest_server/repositories/report/raw_log.py, packages/reporting/src/stories/reports/reporter-side-bar.stories.tsx
All-logs report are now sorted by date desc.
=> reporting:server: Fix all-logs report are sorted by date desc

packages/dashboard/src/components/app.tsx, packages/dashboard/src/components/schedule-visualizer/index.tsx, packages/dashboard/src/managers/trajectory-socket-manager.ts
See linked issue for the screen shot of the error that happens when toggling between panels. In short, the websocket seems to try to connect to the server again when toggling between panels. 
The fix is to check if websocket is ready before sending.
=> send only when websocket is ready

example-deployment/deploy.sh
Signed-off-by: Boon Han <charayaphan.nakorn.boon.han@gmail.com>
Add a timeout of 10 minutes to the example-deployment deploy script. The default value is 30 seconds, which is not always sufficient for keycloak to launch.
=> add a timeout of 10minutes

example-deployment/keycloak-tools/bootstrap-keycloak.js
This PR modifies the deploy.sh script to automatically add the correct client scope and adds it to the dashboard client, so that keycloak authentication works properly. 
Tested on a clean build based on [this commit](https://github.com/open-rmf/rmf/commit/4b25f29e3c08418bf379250a028203ee17f9d12d) of `rmf.repos.`
=> Modify bootstrap file to automatically add dashboard client scope

package-lock.json, packages/react-components/lib/tasks/create-task.tsx
Related to: #364 
`onBlur` api does not behave the same way in firefox and chrome. Clicking on the submit button triggers the onblur api in chrome but does not in firefox. 
In order to be more consistent, the number of loops would be set during `onChange` instead.
=> use onChange instead of onblur

packages/react-components/lib/tasks/task-phases.tsx
Signed-off-by: vallq <val@openrobotics.org>
Revert the phase colors to have red (failed) and green (success) colors
=> revert phase colors, keep success and failed colors

packages/dashboard/src/components/tasks/task-page.tsx
This is part of this mega ticket: https://github.com/open-rmf/rmf-web/issues/352
In short, instead of showing all valid places on the graph, this will only show places that are relevant to the delivery and clean task. As Shown here:
:-------------------------:|:-------------------------:
Dependencies:
- rmf_traffic_editor: `feature/populate-vertex-params`   https://github.com/open-rmf/rmf_traffic_editor/pull/351
- rmf_demos: `feature/cleanup-map-configs` https://github.com/open-rmf/rmf_demos/pull/52
Then run airport world (as it consists both delivery and clean tasks) and the `rmf-web` dashboard
```
ros2 launch rmf_demos airport_terminal.launch.xml
```
- Currently there's a hack going on due to converting `building_map_msgs/Params` to `Record<string, Place>` type, will need to fix this …
=> dashboard: custom dropdown for clean and delivery waypoints

package-lock.json, packages/dashboard/package.json, packages/dashboard/src/components/dashboard/dashboard.tsx, packages/dashboard/src/components/dashboard/tour/tour-map.tsx, packages/dashboard/src/components/schedule-visualizer/dispensers-overlay.tsx, packages/dashboard/src/components/schedule-visualizer/doors-overlay.tsx, packages/dashboard/src/components/schedule-visualizer/index.tsx, packages/dashboard/src/components/schedule-visualizer/robots-overlay.tsx, packages/react-components/lib/doors/door-marker.tsx, packages/react-components/lib/lifts/lift-marker.tsx, packages/react-components/lib/robots/base-marker.ts, packages/react-components/lib/robots/robot-marker.tsx, packages/react-components/lib/robots/trajectory-paths.tsx, packages/react-components/lib/stack-navigator.ts, packages/react-components/stories/benchmarks/robots.stories.tsx, packages/react-components/stories/door-markers.stories.tsx, packages/react-components/stories/robot-markers.stories.tsx, packages/react-components/tests/doors/door-marker.spec.tsx, packages/react-components/tests/robots/default-marker.spec.tsx, packages/react-components/tests/robots/robot-marker.spec.tsx
Many markers are being re-rendered needlessly, testing on the clinic world, these optimizations reduces the render times from ~10ms to ~2ms.
=> perf(dashboad): fix some performance regression in schedule visualizer

packages/api-server/api_server/app.py, packages/api-server/api_server/models/fleets.py, packages/api-server/api_server/routes/fleets.py, packages/api-server/api_server/routes/tasks/dispatcher.py, packages/api-server/api_server/routes/tasks/tasks.py, packages/api-server/api_server/routes/tasks/utils.py
Replace `TaskSummary` in `fleets/robots` with `TaskProgress`.
This should make fetching robot and tasks data much easier in robot panel page.
=> Change fleet/robots task summary to task progress

packages/react-components/lib/robots/robot-table.tsx
(cherry picked from commit 2c0589d81be297c57ffeca0bde0e99c39f09d87b)
Related to #393
Change the `End Time` field of the robot table to `Duration` to better reflect what is displayed on the column.
=> change end time to duration

packages/api-client/lib/index.ts, packages/api-client/lib/openapi/apis/tasks-api.ts, packages/api-client/lib/version.ts, packages/api-client/package.json, packages/api-server/api_server/app.py, packages/api-server/api_server/fast_io.py, packages/api-server/api_server/fast_io/__init__.py, packages/api-server/api_server/fast_io/errors.py, packages/api-server/api_server/rmf_io/__init__.py, packages/api-server/api_server/rmf_io/book_keeper.py, packages/api-server/api_server/routes/tasks/tasks.py, packages/api-server/api_server/routes/tasks/test_tasks.py, packages/api-server/api_server/test/fast_io_app.py, packages/api-server/api_server/test_fast_io.py, packages/dashboard-e2e/tests/ui-interactions.test.ts, packages/dashboard/package.json, packages/dashboard/src/components/tasks/auto-refresh.tsx, packages/dashboard/src/components/tasks/task-page.tsx, packages/dashboard/src/components/tasks/tests/auto-refresh.test.tsx, packages/react-components/lib/robots/robot-table.tsx, packages/react-components/lib/tasks/task-panel.tsx, packages/react-components/lib/tasks/task-phases.tsx, packages/react-components/lib/tasks/task-table.tsx, packages/react-components/stories/tasks/task-panel.stories.tsx, packages/react-components/stories/tasks/task-table.stories.tsx, packages/react-components/tests/tasks/task-panel.spec.tsx, packages/react-components/tests/tasks/task-table.spec.tsx
This adds a button on the task page to toggle auto refresh. "Auto refresh" may different meaning to different people, this PR implements auto refresh like this:
* Currently shown tasks on the task page will be listened for new task updates.
* Auto refresh never changes the ordering or the list of tasks currently shown, only currently shown tasks will be updated.
* Clicking the refresh button will fetch a new set of tasks from the server using the current filter/page settings, this may change the task list and/or the ordering of the tasks.
This means that when a new task is created, it won't appear on the task page without a manual refresh, even if auto refresh is turned on. However, when a task state or status changes, e.g. from `ACTIVE` to `COMPLETED` it will be automatically refreshed …
=> feat(dashboard): auto refresh tasks in task page

packages/reporting-server/parsers/test_auth_event_parser.py, packages/reporting-server/parsers/test_dispenser_state_parser.py, packages/reporting-server/parsers/test_doors_state_parser.py, packages/reporting-server/parsers/test_fleet_state_parser.py, packages/reporting-server/parsers/test_health_parser.py, packages/reporting-server/parsers/test_ingestor_parser.py, packages/reporting-server/parsers/test_lift_state_parser.py, packages/reporting-server/parsers/test_task_summary_parser.py, packages/reporting-server/rest_server/__mocks__/parsed_data.py, packages/reporting-server/rest_server/__mocks__/raw_data.py, packages/reporting-server/rest_server/repositories/test_log_creation_handler.py, packages/reporting-server/rest_server/repositories/test_parser_dispatcher.py, packages/reporting-server/rest_server/routers/test_log.py
The data being received from fluentd was being replicated in several places. What was done in this PR is to place all the mocks in one place, so if the structure changes we should change it in one place and if the tests fail it will be easier to detect.
=> reporting-server: refactor reporting-server with mocks

example-deployment/docker/builder.dockerfile
Signed-off-by: Boon Han <charayaphan.nakorn.boon.han@gmail.com>
Currently, the variable RMF_SERVER_USE_SIM_TIME, which is important for setting sim time configuration on the api-server, is not configured. When it is not configured, it seems the default behavior is to treat it as false. This can be confusing.
By setting this in the builder dockerfile, this configuration can propagate.
=> set RMF_SERVER_USE_SIM_TIME variable concretely in example-deployment

example-deployment/docker/builder.dockerfile
When I tried to build the `builder.dockerfile`, I got this error
```
Error response from daemon: failed to parse .dockerfile.c9a48f26a800b30066d5: Syntax error - can't find = in "#". Must be of the form: name=value
```
After some digging I realized It was because of the comment here
```
ENV RMF_SERVER_USE_SIM_TIME=true # Set this based on your use_sim_time configuration when launching the backend
```
=> fix/ error on building builder.dockerfile

example-deployment/docker/dashboard.dockerfile, example-deployment/docker/reporting.dockerfile, example-deployment/k8s/reporting.yaml, example-deployment/keycloak-tools/bootstrap-keycloak.js
The root cause is because `/etc/nginx/conf.d/default.conf` already contains a `location / {}` block and that conflicts with the declaration in `/etc/nginx/conf.d/reporting.conf`. The reason it works in dashboard is because `dashboard.conf` gets loaded before `default.conf` because or file system sorting ("da" comes before "de").
This also adds the admin user for use with the new authorization changes. It should be used in favor of "example" when performing some things like submitting tasks.
=> fix(example-deployment): fix reporting infinite redirect

packages/api-server/api_server/routes/tasks/dispatcher.py, packages/api-server/api_server/routes/tasks/tasks.py, packages/dashboard/src/components/tasks/task-page.tsx
=> submit task sequentially

example-deployment/README.md, packages/api-server/api_server/gateway.py, packages/dashboard/rmf-launcher.js
- change task status subscribtion topic  from `task_summaries` (rmf_tasks_msgs/TaskSummary) to `dispatcher_ongoing_tasks` (`rmf_task_msgs.msg/Tasks`). To filter properly cancel self-allocated tasks and remove `ResponsiveWait` Tasks. https://github.com/open-rmf/rmf_ros2/pull/60
- rmf_demos scenarios launcher pkg to `rmf_demos_gz` https://github.com/open-rmf/rmf_demos/pull/78
=> Fix on task_summaries topic and switch launcher pkg rmf_demos_gz

packages/dashboard/src/components/dashboard/dashboard.tsx
Fixes https://github.com/open-rmf/rmf-web/issues/496 by doing a shallow copy that forces a render.
Naively I am understanding there are some drawbacks to using [shallow copies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign), but i'm not sure if they are relevant in our case. The alternative deep copy seems to be `JSON.parse(JSON.stringify())`.
It is taking about 1 seconds to load icons now switching tabs away / back to the buildings tab, when before it took minimal time, i'm wondering if that is something that can be fixed.
=> clone objects to trigger rendering

packages/api-server/api_server/app.py
Signed-off-by: Charayaphan Nakorn Boon Han <charayaphan.nakorn.boon.han@gmail.com>
Thanks @ChawinTan  for the help!
Use `from_tortoise` function to replace undefined usage of `to_pydantic` in `app.py`.
fixes https://github.com/open-rmf/rmf-web/issues/478
Additional Questions:
It seems that `for_tortoise` for Health objects vs State objects have different sync/async properties now. Is this something we should address?
Health objects have async definition
https://github.com/open-rmf/rmf-web/blob/main/packages/api-server/api_server/models/health.py#L36
Door objects have sync definition
https://github.com/open-rmf/rmf-web/blob/main/packages/api-server/api_server/models/doors.py#L14
=> use from_tortoise instead of to_pydantic

packages/dashboard/src/components/schedule-visualizer/index.tsx
fixes #514
<b>Before</b>
https://user-images.githubusercontent.com/29136440/139360824-e68ed8e8-cb45-404f-aa81-83910361fb4d.mp4
<b>After</b>
https://user-images.githubusercontent.com/29136440/139360832-7d9839c7-6ad7-4fbb-9a3c-bca06603df5e.mp4
Previously, the robot icons were loaded one interval after the rest of the items. With this fix, everything is now loaded together on the first interval.
There are 2 separate useEffects that is used to handle the rendering of fleets. Previously, the second useEffect was executed when robotStore was still empty due to the asynchronous nature of the code in the first useEffect. As a result,  the robot icons only appeared on the second interval.
Shifting the block of code to the first useEffect and executing …
=> Fix - long icon rendering time

.npmrc, package-lock.json, package.json, packages/api-client/package.json, packages/api-client/tsconfig.json, packages/api-server/package.json, packages/dashboard-e2e/package.json, packages/dashboard/package.json, packages/dashboard/tsconfig.json, packages/react-components/package.json, packages/react-components/tsconfig.json, packages/reporting/package.json, packages/reporting/tsconfig.json, packages/rmf-auth/package.json, packages/rmf-auth/tsconfig.json, scripts/current-package.js, scripts/nws.sh, scripts/workspace-args.js
Cause is because the bootstrap script does not automatically build all packages. The fix is to add a custom script to build all dependencies in the correct order in the `start` script.
This also adds the engine field in the root package.json to avoid running it with unsupported npm version.
=> build: fix `npm start` immediate after bootstrap not working

packages/api-server/.gitignore, packages/api-server/api_server/app_config.py, packages/api-server/api_server/default_config.py, packages/api-server/api_server/ros.py, packages/api-server/package.json, packages/api-server/psql_local_config.py, packages/api-server/sqlite_local_config.py
* Adds `ros_arg` option to config.
* `RMF_SERVER_USE_SIM_TIME` takes precedence over the config file.
* `npm start` uses disk-backed sqlite3 (app default is still in memory sqlite3)
* `npm start` uses sim time by default (app default is still no sim time)
These defaults, along with the recent change of `clock.py` to use ros time should allow relative `between` query to work as expected.
=> build: tasksv2/better dev defaults

packages/dashboard/README.md, packages/dashboard/package.json
With more testing and demos running on the dashboard, it would be helpful to have the default start script only start up the backend servers, dashboard building and launching, without start headless simulation instances.
I checked around and it doesn't look like we are using `npm start` for the dashboard anywhere else. Just in case I missed out on anything, @koonpeng @mayman99 do you all know anywhere that may be broken due to this change? (e.g. e2e testing, CI, etc)
=> Changing default start script

packages/api-client/lib/openapi/api.ts, packages/api-client/lib/version.ts, packages/api-client/schema/index.ts, packages/api-server/api_server/models/__init__.py, packages/api-server/api_server/routes/tasks/tasks.py
This PR aims to add direct robot assignment REST api calls in the rmf_server, following this: https://github.com/open-rmf/rmf_demos/blob/redesign_v2/rmf_demos_tasks/rmf_demos_tasks/direct_patrol.py
=> Add direct robot assignment api call

packages/api-server/api_server/models/tortoise_models/log.py
Originated from https://github.com/open-rmf/rmf-web/pull/603
Previously will get receive an error printout when the timestamp is more than 32bit `IntField` .
=> log time with 64 bit

Pipfile, Pipfile.lock, packages/api-server/setup.py, packages/reporting-server/setup.py
This PR updates dependencies in rmf-web to be compatible with Python 3.10, shipped in Ubuntu 22.04, default release for Humble.
Specifically:
* `uvicorn` to [0.16.0](https://github.com/encode/uvicorn/releases/tag/0.16.0), bumping websockets to a version that is compatible with Python 3.10
* `asyncpg` to latest, Python 3.10 support added in [0.24.0](https://github.com/MagicStack/asyncpg/releases/tag/v0.24.0)
I honestly don't know much about how `Pipfile` works, it specifies a version of `requests` that is technically not compatible with Python 3.10 and seems to force Python 3.8, however in docker builds it seems to be OK. Didn't change those since I don't know what implications they might have
=> Humble / 22.04 compatibility

packages/api-server/api_server/routes/tasks/tasks.py
Originated from https://github.com/open-rmf/rmf-web/pull/603
This is related to the direct assignment call when calling the `/robot_task` REST API. The request works, but response body is incorrect, hence the fix.
Test the `/robot_task` endpoint on `http://localhost:8000/docs`  with the json request body below: (rmf_demos's office world)
```json
{
"type": "robot_task_request",
"robot": "tinyRobot1",
"fleet": "tinyRobot",
"request": {
"unix_millis_earliest_start_time": 0,
"category": "patrol",
"description": {
"places": [
"pantry",
"lounge"
],
"rounds": 2
}
}
}
```
=> fix response body for robot_task

packages/react-components/lib/tasks/create-task.tsx
PR originated from: https://github.com/open-rmf/rmf-web/pull/603
With the new `patrol` task (previously known as `Loop`), the task form accepts a list of places, instead of a pair of `start` and `end` places. Thus this form is to make the second place optional, helping dispatch the robot to a single location. Also, with the new `patrol` task, the number of loops is changed to `rounds`
=> accept single place for loop task form

packages/api-server/api_server/fast_io/__init__.py
Since upgrading uvicorn (probably from #617), you may get `tortoise.exceptions.ConfigurationError: No DB associated to model` errors. This is due to the app startup not being called at all, while I'm not sure of the root cause, switching the main asgi app to fastapi fixes it.
=> api-server: fix fastio to work with newer uvicorn

Pipfile
This PR adds numpy as one of the packages to install. Without it I got a `ModuleNotFoundEror: No module named 'numpy'` and is unable to launch rmf-web
=> Add numpy to pipfile

packages/api-server/api_server/routes/internal.py
For some instance when running rmf_demos, i will get this error:
```
await dependant.call(**values)
File "/usr/local/lib/python3.8/dist-packages/api_server/routes/internal.py", line 49, in rmf_gateway
await process_msg(msg, fleet_repo)
File "/usr/local/lib/python3.8/dist-packages/api_server/routes/internal.py", line 18, in process_msg
payload_type: str = msg["type"]
TypeError: list indices must be integers or slices, not str
```
I noticed some client is sending in an msg data with empty array `[]`, which is not compatible to the rmf msg. This requires further investigation to fix this. Meanwhile, the api server should also be robust enough to pick up incompatible msg, thus a simple safe check to ensure 'type' exists in the msg field.
=> safe check internal ws msg 'type' field

packages/api-server/package.json, packages/dashboard/package.json
Running `start:psql` in `packages/dashboard` still runs with `RMF_API_SERVER_CONFIG=sqlite_local_config.py`, this changes it to the correct `psql_local_config.py`
=> Fix starting with psql

README.md
This PR adds an installation step in the README to install `python3-venv` for Ubuntu/Debian systems. It also corrects the launch instructions from `npm install` to `pnpm install`
=> Update installation steps in readme

packages/dashboard/src/components/map-app.tsx
* https://github.com/open-rmf/rmf-web/pull/667 - allows us to split default zoom level and event zoom level
* c44405d3d1c23b1344b3e953e4daaa84217f386b: changes default zoom level to be 2.5
https://user-images.githubusercontent.com/5383623/215057715-9a26e6c9-6b6b-4f78-b609-d60f7a21010c.mp4
=> [Wrench] different zoom levels

Pipfile.lock
This reverts commit 7600f6c9fae9becb258665baea3eed138979f607, #674 
This broke `api-server` during runtime, due to unsupported version.
https://gist.github.com/aaronchongth/1ea0fc3a8fc503e2d6ee18a9e223e120
=> Revert "build(deps): bump cryptography from 38.0.4 to 39.0.1 (#674)

.github/workflows/nightly.yml
Fix nightly failure due to denied permissions during cleanup of workspace, similar to https://github.com/actions/checkout/issues/211.
=> Resolving permissions issue when cleaning up github runner workspace

packages/api-server/generate-models.sh, packages/api-server/package.json
fix wrong version of `datamodel-codegen` being used. Also removed the check that rmf is not sourced, the check is added due to colcon's "include pollution bug/feature" which is now largely mitigated as rmf is using "isolated" include dir (e.g. `/opt/ros/humble/include/rmf_door_msgs/rmf_door_msgs`).
=> fix wrong version of `datamodel-codegen` being used

Pipfile.lock
First step of https://github.com/open-rmf/rmf-web/issues/695
=> Rollback setuptools to 65.6.3 to avoid PEP440 issues with >=66.0.0

.github/workflows/dashboard-e2e.yml, .github/workflows/nightly.yml
Using `nick-fields/retry@v2` for flaky `dashboard-e2e` workflow tests.
The proper fix should be resolving what is making the e2e tests flaky, keeping this as a draft for consideration while we continue down our roadmap.
=> Retry on dashboard e2e workflows

packages/dashboard/src/components/robots/robot-summary.tsx
I just noticed that the series of battery icons that we were using didn't cover empty battery levels :facepalm: I played around with the icons and tried to use integers instead of strings as keys. 
I had concerns that we are assuming the keys will always be sorted from low to high numbers, but I couldn't find a better solution. I think we can stick to the concept you had
=> Using all battery bar icons with unknown and empty

packages/dashboard/src/components/robots/robot-summary.tsx, packages/dashboard/src/components/robots/robots-app.tsx, packages/dashboard/src/components/robots/robots-workspace.tsx
Popup dialog to show robot summary
- Removed micro app (Robot info) from the top right of the robot section
- Added a robot summary with the most relevant data
- Robot summary popup has a button to show  Task Inspector
- The map is shown on the right
[chrome-capture-2023-3-27.webm](https://user-images.githubusercontent.com/37310205/234994779-71149660-9c90-4277-8da5-fede07776b4e.webm)
=> Show up robot summary when user click robot row

packages/dashboard/src/components/robots/robots-app.tsx, packages/react-components/lib/robots/index.ts, packages/react-components/lib/robots/robot-table-datagrid.spec.tsx, packages/react-components/lib/robots/robot-table-datagrid.stories.tsx, packages/react-components/lib/robots/robot-table-datagrid.tsx
- Migrate robot table to datagrid mui
- New test file was added
- New storybook file was added
- Removed the use of the basic table and instead used mui's datagrid. 
- Allow the frontend to do all the sorting and filtering since we do not need to handle pagination.
[chrome-capture-2023-5-1.webm](https://github.com/open-rmf/rmf-web/assets/37310205/8ff970ff-b541-4290-acdb-5d62e816b0bb)
=> Migrate robot table to datagrid

packages/dashboard/src/components/appbar.tsx, packages/dashboard/src/components/tasks/tasks-app.tsx
- Hover tooltips were added in appbar and taskapp
[chrome-capture-2023-5-15.webm](https://github.com/open-rmf/rmf-web/assets/37310205/e47c48c6-7c29-475f-af94-1cc977f03716)
=> Add hover tooltips

packages/react-components/lib/tasks/create-task.tsx
* Fixed sizing and spacing of forms using material ui spacing and grid containers
=> Make forms look nicer

packages/api-server/api_server/models/tortoise_models/scheduled_task.py, packages/dashboard/src/components/appbar.tsx, packages/react-components/lib/tasks/create-task.tsx
- End date added for recurring tasks
- Ending date is inclusive
- Create a scheduled task. 
- Choose the ON option under "Ends" and set an until date.
- The scheduling screen should show only tasks up to the chosen date. 
[chrome-capture-2023-6-21.webm](https://github.com/open-rmf/rmf-web/assets/37310205/9f265ad0-12c1-4181-8631-8230d1aa60e1)
=> Ends on scheduling recurrences

packages/api-server/api_server/rmf_io/health_watchdog.py
=> Catching MultipleObjectsReturned, logging that only a single map is supported

packages/dashboard/src/components/appbar.tsx, packages/react-components/lib/map/trajectory-time-control.tsx
- Fix react 18 warning. (React.render)
- Fix the correct functioning of the tabs
- Appbar tab displays the wrong tab
- React 18 warning
- The appbar displays the selected tab correctly. 
[chrome-capture-2023-7-1.webm](https://github.com/open-rmf/rmf-web/assets/37310205/7acbf083-3198-4a7a-b860-c6d3cc96fbdd)
- The warning no longer appears.
=> Fix react 18 warning and show appbar tab correctly

packages/api-server/api_server/models/building_map.py
Ensures that the map saved in db is always the one that is currently being served by the building map server.
This can be tested by starting an api-server instance, and changing the building map server,
```
pnpm start
ros2 run rmf_building_map_tools building_map_server WORKSPACE_DIR/install/rmf_demos_maps/share/rmf_demos_maps/office/office.building.yaml
ros2 run rmf_building_map_tools building_map_server WORKSPACE_DIR/install/rmf_demos_maps/share/rmf_demos_maps/airport_terminal/airport_terminal.building.yaml
```
=> Deletes all existing building map entries if the id does not match the current served map, before saving

packages/dashboard/src/components/map-app.tsx
Related to https://github.com/open-rmf/rmf-web/issues/734
* Use orthographic camera by default
* Target of orthographic camera set to 1km below origin, this fixes the re-orientation when we pan
* Changing left click to panning
* Disabling all other mouse interations (rotation and dolly)
* Using a fixed zoom of 20 for now, this should be configurable later on
=> Fix panning rotation issue

pnpm-lock.yaml
Updates `caniuse-lite` so the annoying prompt about updating browerslist doesn't show up anymore.
=> Update browserslist and caniuse-lite

packages/dashboard/src/components/app.tsx
Fix some missing migrations when upgrading to react router v6.
=> fix login page route

packages/dashboard/src/components/app.tsx, packages/dashboard/src/components/appbar.tsx
=> Remove custom and admin tabs

packages/dashboard/src/components/appbar.tsx, packages/react-components/lib/place.ts, packages/react-components/lib/tasks/create-task.tsx
Fixes to broken delivery task request
* re-introduced the `handler` field for pickup and dropoff
* reverted back to `getPlace` function call, but changed the implementation to return information for all types of named places
* create-task now accepts a `Record<string, string>` for pickup and dropoff points, as it maps the name of the waypoint to the name of the handler
* checks for valid pickup and dropoff waypoint names and handler names before triggering change, to prevent crashes in the backend
* fixed a minor typo where modifying dropoff location changes pickup locations too
=> Fixing missing handler delivery task description

packages/dashboard/src/components/app-events.ts, packages/dashboard/src/components/map-app.tsx
Setting default zoom value to 0.5.
=> Hammer zoom

packages/api-client/lib/openapi/api.ts, packages/api-client/lib/version.ts, packages/api-client/schema/index.ts, packages/api-server/api_server/models/tortoise_models/scheduled_task.py, packages/api-server/api_server/routes/tasks/scheduled_tasks.py, packages/dashboard/src/components/tasks/tasks-app.tsx
- New field added into ScheduleTask model. `except_dates`. An array that stores the dates that the user does not want a job to run. 
- Added an endpoint to regenerate the schedule based on exception days. 
- Added a pop-up with the option to delete all events or just the selected event. 
[chrome-capture-2023-7-22.webm](https://github.com/open-rmf/rmf-web/assets/37310205/878a158f-a35f-43a8-9394-a292ab16a101)
[chrome-capture-2023-7-22 (1).webm](https://github.com/open-rmf/rmf-web/assets/37310205/8901584e-9d3d-4190-8d31-f8076e251f35)
=> Delete the entire recurring event or only the selected event

packages/react-components/lib/tasks/create-task.tsx
- Removed the button to load tasks
- Centered the title of the form
=> Task form changes

packages/dashboard/src/components/appbar.tsx, packages/react-components/lib/window/window-toolbar.tsx
- Increase the font size on the title bar 
- Change New Task button size
=> App bar changes

packages/dashboard-e2e/tests/ui-interactions/index.test.ts, packages/dashboard-e2e/tests/ui-interactions/submit-task.test.ts
Changing task submission e2e test to `Delivery`
=> Turning off submit task tests for sanity check

packages/react-components/lib/tasks/create-task.tsx
Fix dropoff points for hunting delivery tasks.
=> Dropoff points to show waypoint/place names instead of ingesters

packages/react-components/lib/tasks/create-task.tsx
Selecting a favorite task set it as the main task, instead of appending it to a list of task.
This fixes the issue of including the default task.
=> Selecting a favorite task changes taskRequests, instead of append

.github/actions/bootstrap/action.yml
=> Reverting to latest pnpm version when #6994 is fixed

packages/dashboard-e2e/wdio.conf.js, packages/dashboard/src/components/app-base.tsx
Displays an alert if the display resolution is low.
https://github.com/open-rmf/rmf-web/assets/5383623/d5b12cea-0a44-4a21-a634-237818fc29da
=> Display an alert when low display res detected

packages/dashboard-e2e/tests/ui-interactions/submit-task.test.ts, packages/react-components/lib/tasks/create-task.tsx
Renaming to `delivery_sequential_lot_pickup` and `delivery_area_pickup`
=> Renamed hammer categories

packages/dashboard/package.json
Changing start and start:react scripts
=> start:react builds dependencies before starting dashboard, start just runs the concurrently command

packages/api-client/lib/openapi/api.ts, packages/api-client/lib/version.ts, packages/api-client/schema/index.ts, packages/api-server/api_server/routes/tasks/scheduled_tasks.py, packages/dashboard/src/components/appbar.tsx, packages/dashboard/src/components/tasks/task-schedule-utils.ts, packages/dashboard/src/components/tasks/task-schedule.tsx, packages/dashboard/src/components/tasks/tasks-app.tsx, packages/dashboard/src/components/tasks/utils.ts, packages/dashboard/src/hooks/useCreateTaskForm.tsx, packages/dashboard/src/hooks/useFetchUser.tsx, packages/react-components/lib/tasks/create-task.tsx, packages/react-components/lib/tasks/index.ts, packages/react-components/lib/tasks/task-schedule-event-edit-delete-popup.spec.tsx, packages/react-components/lib/tasks/task-schedule-event-edit-delete-popup.tsx
=> Port schedule editing to hammer

packages/dashboard/src/components/map-app.tsx, packages/react-components/lib/map/three-fiber/image-maker.tsx
=> Small fixes to react-three-fiber migration

packages/api-server/api_server/routes/tasks/scheduled_tasks.py, packages/dashboard/src/components/tasks/task-schedule-utils.ts
* Fix editing single event setting the correct date
* Add toIsoFormat
* format date to isoFormat
* Format to isoFormat
* Revert to exceptDateref insted of the schedule request time
---------
(cherry picked from commit c9c4570594d102a62c70863ec130b03aa6fdbe07)
=> Fix - schedule single event (#791)

packages/react-components/lib/lifts/lift-request-dialog.tsx
Fix logic error where the value `0` will trigger changing lift request type to the first in the list.
=> Detect 0 as number as well

.github/workflows/dashboard.yml, packages/dashboard/src/components/three-fiber/robot-three.tsx, packages/react-components/lib/map/three-fiber/robot-three-maker.tsx, packages/react-components/package.json
* Fixing max heap size for allocation on dashboard unit test.
* Remove stale use of `Hatchback` mesh
* Remove use of mesh for model
TODO:
* use dashboard resources to target an image to be used for robots
* use dashboard resources to set scale of such images (meters per pixel)
=> Fix dashboard CI for react-three-fiber migration

packages/dashboard/src/components/map-app.tsx
* Rename `Labels` to `Doors and lift labels`
* Only display dropoff point labels by default
=> Rename door and lift labels and only display dropoff waypoint labels by default

packages/dashboard/src/components/three-fiber/camera-control.tsx
The issue 
[chrome-capture-2023-9-12 (1).webm](https://github.com/open-rmf/rmf-web/assets/37310205/e9881d17-0080-4605-8e9c-aa0a9e0e6eee)
The fix
- Use gl.domElement to point to the DOM element associated with the Three.js renderer and not to the global dom.
[chrome-capture-2023-9-12 (2).webm](https://github.com/open-rmf/rmf-web/assets/37310205/f11a5fcc-f437-4bb3-9dd4-5a5259316ef8)
=> Fix wheel behavior 

packages/dashboard/src/components/map-app.tsx, packages/dashboard/src/components/three-fiber/robot-three.tsx
Debugging issue where building map is not retrieved while waypoints are rendered.
* More logs and more checks (to be removed)
* Fixed a race condition where robot locations have not come in yet
* Get building map explicity before setting up subscriptions
=> Adding console logs and getting building map manually alongside subscription

packages/api-client/lib/openapi/api.ts, packages/api-client/lib/version.ts, packages/api-client/schema/index.ts, packages/api-server/api_server/gateway.py, packages/api-server/api_server/models/lifts.py, packages/api-server/api_server/routes/lifts.py, packages/api-server/api_server/routes/test_lifts.py, packages/dashboard/src/components/lifts-app.tsx
Lift end session behavior changes
* modifies `LiftRequest` model to accept additional session IDs
* requests will be published per normal, with additional publishes to each additional session ID
* on the frontend, the additional session IDs are only added if the request type is End Session
* additional session IDs are formatted as `fleet_name/robot_name`, by querying the fleet get API
https://github.com/open-rmf/rmf-web/assets/5383623/5211b82f-9fe7-4fee-a516-70135bc7d731
=> Close session to handle additional session IDs

packages/api-server/api_server/authenticator.py, packages/dashboard/src/components/tasks/task-details-app.tsx, packages/dashboard/src/components/tasks/task-inspector.tsx
Temporarily remove admin requirement for cancellation.
=> Removing admin requirement for task cancellation

packages/react-components/lib/map/three-fiber/robot-three-maker.tsx
Fix issue where font needs to be downloaded during runtime.
=> Fix oddly failing robot label and use same as other labels

packages/react-components/lib/map/three-fiber/lift-three-maker.tsx
Last instance of Text font requirement, in the event the lift is in an undefined state.
=> For handling undefined states

packages/dashboard/src/components/map-app.tsx, packages/dashboard/src/components/three-fiber/robot-three.tsx, packages/dashboard/src/managers/__mocks__/resources.ts, packages/dashboard/src/managers/resource-manager-robots.ts, packages/react-components/lib/map/three-fiber/robot-three-maker.tsx, packages/react-components/lib/map/three-fiber/shape-three-rendering.tsx, packages/react-components/lib/map/three-fiber/text-maker.tsx
- Display robot icons as images in react three fiber. 
- Make waypoints square smaller. 
- Make waypoints transparent
=> Using icon to display robot

packages/api-server/api_server/models/delivery_alerts.py, packages/api-server/api_server/models/tortoise_models/delivery_alerts.py, packages/dashboard/src/components/delivery-alert-store.tsx
* Works with https://github.com/open-rmf/rmf_internal_msgs/commit/0997d89ae93efd1a06359d5f4270bf3738e5160c
* Added `obstructed` and `cancelled` delivery alert category
* For `obstructed`
* no UI action needed, message will instruct users to move things out of the way of the robot
* user can close the alert, but if the dashboard is refreshed, it will pop out again if the obstruction is still ongoing
* once fleet adapter is able to continue, it will send another delivery alert request with the same IDs to update action to `resume`, the delivery alert will then stop showing up
* For `cancelled`
* we expect it to only have tier `error`
* if however a tier `warning` comes through, it will be promoted to tier `error` with a console warning
* no user interaction expected, they can only close it …
=> Obstructed and Cancelled delivery alert category with desired behaviors

packages/dashboard/src/components/tasks/task-schedule.tsx, packages/dashboard/src/components/tasks/tasks-app.tsx
* Separated `Day`, `Week`, `Month` view change buttons away from `Today` as it is confusing what those buttons do together
* Change text of `Today` button based on view
=> Rearrange schedule view, with better word prompts

packages/react-components/lib/confirmation-dialog.tsx, packages/react-components/lib/tasks/create-task.tsx
- Decrease font size as the screen gets smaller
=> Create task form - Adapting styles according to resolution

packages/dashboard/src/components/delivery-alert-store.tsx, packages/dashboard/src/components/tasks/task-schedule.tsx, packages/react-components/lib/tasks/create-task.tsx
* Fix schedule change day, week, month view (revert to original design provided by library)
* Allow resume if obstruction delivery alert is due to a latching problem 
* Sort option fields in task creation form, except for Cart IDs
=> If the obstruction is related to a latching issue, allow resume

packages/api-server/api_server/app.py, packages/api-server/api_server/authenticator.py, packages/api-server/api_server/routes/tasks/scheduled_tasks.py, packages/api-server/psql_local_config.py, packages/dashboard/src/components/app-events.ts, packages/dashboard/src/components/tasks/task-schedule.tsx
* Catch exception when server loads an old schedule from DB and it is invalid (because it is in the past)
* try catch for deletion of scheduled tasks events and scheduling a new one
* Fix psql script
* Fix constantly updating schedule app with new refresh task app event only for scheduler
=> Catch failure to load old schedules in database

packages/dashboard/src/components/app-events.ts, packages/dashboard/src/components/appbar.tsx, packages/dashboard/src/components/rmf-app/rmf-ingress.ts, packages/react-components/lib/lifts/lift-request-dialog.tsx, packages/rmf-auth/lib/keycloak.ts
Various frontend changes and potential fix to auth issue
* selecting lift end session will disable all other options
* favorite tasks have its own event trigger, reducing the amount of task queue table recurring polling
* increasing the token refresh allowance to 30 seconds
* logs axios error during request or response, attempts to move client to route `/`
* alert when the client disconnects (WIP)
=> Frontend changes, more auth logs, relax token refresh interval

packages/ros-translator/package.json, pnpm-lock.yaml
Revert versions for jasmine and ts-node to get tests working again.
=> Revert jasmine and ts-node versions

packages/dashboard/src/components/appbar.tsx, packages/dashboard/src/managers/resource-manager.ts, packages/react-components/lib/tasks/create-task.tsx
* `emergencyLots` added to `resourceManager`
* updated task json for deliveries and custom deliveries
=> Task json that accommodates on-cancel emergency lots

packages/dashboard/src/components/tasks/tasks-app.tsx
Remove individual task updates, to prevent bandwidth issues when lots of tasks are queued or ongoing.
=> Remove individual task subscriptions

packages/api-server/api_server/routes/tasks/scheduled_tasks.py
Change scheduled tasks' request time to current time.
=> Change scheduled tasks' request time

packages/react-components/lib/tasks/create-task.tsx
Zero out seconds and milliseconds of schedule start times, to avoid skipping scheduled tasks
=> Seconds and milliseconds of start time to be zero

packages/api-server/api_server/app_config.py, packages/api-server/api_server/default_config.py, packages/api-server/api_server/routes/internal.py
Implements an optional static limit to the number of internal websocket connections allowed. Supercedes https://github.com/open-rmf/rmf-web/pull/895
Temporary fix for https://github.com/open-rmf/rmf-web/issues/897
* Removes `WebsocketHealthManager`, just uses `ConnectionManager`
* New configurable parameter `max_internal_websocket_connections`. This value should be number of fleet adapters using `BroadcastClient` + number of task dispatchers
To test
* add `"max_internal_websocket_connections": 1,` to `packages/api-server/sqlite_local_config.py`, we only allow one fleet adapter connection
* launch office demo, `ros2 launch rmf_demos_gz office.launch.xml server_uri:="ws://localhost:8000/_internal" headless:=1`, this launches `rmf_task_dispatcher` without server connection at the moment
* in …
=> Shuts down server if internal websocket connections exceed max allowed defined in config

packages/api-server/api_server/app_config.py, packages/api-server/api_server/default_config.py, packages/api-server/api_server/routes/tasks/scheduled_tasks.py, packages/api-server/api_server/routes/tasks/test_scheduled_tasks.py, packages/api-server/scripts/sqlite_test_config.py, packages/dashboard/src/components/tasks/task-schedule-utils.ts, packages/dashboard/src/components/tasks/task-schedule.tsx, packages/dashboard/src/components/tasks/tests/task-schedule-utils.test.tsx
* Added more tests on the route level
* Convert incoming except dates (in UTC) to any local timezones defined for the server, to determine the dates for `except_dates` 
* Fix the dashboard renders schedules.
* deleting a task on day 1 before 8am results in day 2's task not being rendered, because day 1 is added into `except_date`, but `toISOFormat` checks in UTC, which makes day 1 -> day 0, and day 2 -> day 1, therefore failing to render day 2's
Before:
* we extract the date (YYYY-MM-DD) from the provided UTC dates, however this doesn't take into account of the case where UTC and server TZ has different dates (before Singapore 8am, for example). Currently this affects deleting or editing schedules before 8am only
* Example scenario, deleting a schedule at `05:00 GMT+8 2024-02-09`, will …
=> Schedule deletion: fix date differences due to different timezones, more tests

packages/api-server/.pylintrc, packages/api-server/api_server/routes/tasks/scheduled_tasks.py, packages/api-server/api_server/routes/tasks/test_scheduled_tasks.py, packages/dashboard/src/components/tasks/task-schedule.tsx
Similar to https://github.com/open-rmf/rmf-web/pull/896, but for schedule editing
* Convert schedule update exempted date to server timezone before appending to except
* make dashboard edit except date have time zone information
* tests
=> Update schedule with timezone information

packages/api-server/api_server/routes/tasks/scheduled_tasks.py, packages/dashboard/src/components/alert-store.tsx, packages/dashboard/src/components/tasks/task-alert.tsx
* Logs new scheduled task
* Closes acknowledged task alert after clicking ack (Before this, the alert dialog would only be updated with ack information, so 2 clicks + some delay were needed to fully ack and close a task alert dialog)
=> Logging for schedule creation, simplify alert ack

packages/dashboard/src/components/lift-summary.tsx, packages/dashboard/src/components/lifts-app.tsx, packages/react-components/lib/lifts/lift-table-datagrid.tsx
In scenarios with multiple robots sharing a lift, it is not evident to the user which robot has control of the lift if they are all queuing up for it. This will allow users to recognize which robot has control and be able to recover from manual interventions by cancelling the correct robot's task.
* Displaying lift summary again
* Adding session ID into summary information
=> Display lift session ID for lift summary

.github/actions/bootstrap/action.yml
node16 has been EOL for some time now and the latest version of pnpm no longer supports it. This is a temporary workaround to get ci to run, #913 already updates to node20 but we need to merge deploy/hammer into main as well.
=> pin pnpm version to workaround node16 eol

packages/dashboard/src/components/tasks/tasks-app.tsx
Fix issue where export loading screen goes on forever when no export tasks are available.
=> Remove background loading if no tasks were found

packages/api-client/lib/openapi/api.ts, packages/api-client/lib/version.ts, packages/api-server/api_server/routes/delivery_alerts.py, packages/dashboard/src/components/delivery-alert-store.tsx
=> Disable cancel button if there is a latching failure

packages/api-server/api_server/repositories/tasks.py
Revert use of mutex and lock for task state saving, catch exception instead.
=> Reverted use of asyncio.Lock, just catch exceptions instead

packages/api-server/api_server/authenticator.py
`DecodeError` is not broad enough to catch errors that might cause auth to fail (e.g. expired tokens). The result is that the error is uncaught and the server returns 500. This fixes it so it properly return 401.
=> api-server: catch invalid token error

packages/api-client/lib/openapi/api.ts, packages/api-client/lib/version.ts, packages/api-client/schema/index.ts, packages/api-server/api_server/models/__init__.py, packages/api-server/api_server/models/labels.py, packages/api-server/api_server/models/task_booking_label.py, packages/api-server/api_server/query.py, packages/api-server/api_server/repositories/tasks.py, packages/api-server/api_server/rmf_io/test_rmf_service.py, packages/api-server/api_server/routes/tasks/tasks.py, packages/api-server/api_server/routes/tasks/test_tasks.py, packages/api-server/api_server/test/__init__.py, packages/api-server/api_server/test/test_client.py, packages/api-server/api_server/test/test_data.py, packages/api-server/api_server/test/test_fixtures.py, packages/api-server/api_server/test_sio_auth.py, packages/api-server/scripts/test.py, packages/dashboard/src/components/tasks/tasks-app.tsx
Supports labels without requiring the schema to be strongly defined. This is still a bit hacky, it still assumes the label is a json with a `description` field while labels in RMF are free-form strings. RMF needs to support key value pair labels for us to be able to use them "natively".
Another issue is that tortoise-orm is lacking many features which prevent us to implement proper sorting on generic labels so we must still use hacks for the `pickup` and `destination` fields. We could use raw sql for this or drop support for sorting by labels.
=> api-server: Support generic labels

packages/api-server/api_server/app.py, packages/api-server/api_server/models/__init__.py, packages/api-server/api_server/models/rio.py, packages/api-server/api_server/models/tortoise_models/__init__.py, packages/api-server/api_server/models/tortoise_models/rio.py, packages/api-server/api_server/rmf_io/__init__.py, packages/api-server/api_server/rmf_io/events.py, packages/api-server/api_server/routes/__init__.py, packages/api-server/api_server/routes/rios.py, packages/api-server/api_server/routes/test_rios.py, packages/api-server/api_server/test/test_fixtures.py, packages/api-server/generate-models.sh
A set of endpoints for RIO (Robot Interaction Objects), a simple system to represent generic "objects" which can be tracked by RMF. For now this is just endpoints to store and query RIO. There is no usage of RIO in RMF yet, this is just an initial data structure to facilitate future integrations.
=> api-server: first impl of rio

packages/api-server/api_server/app.py, packages/api-server/api_server/models/__init__.py, packages/api-server/api_server/models/rio.py, packages/api-server/api_server/models/tortoise_models/__init__.py, packages/api-server/api_server/models/tortoise_models/rio.py, packages/api-server/api_server/rmf_io/__init__.py, packages/api-server/api_server/rmf_io/events.py, packages/api-server/api_server/routes/__init__.py, packages/api-server/api_server/routes/rios.py, packages/api-server/api_server/routes/test_rios.py, packages/api-server/api_server/test/test_fixtures.py
* first impl of rio
* fix lint
* cleanup
* add option to reset app before each test
* fix lint
---------
(cherry picked from commit 764c551353dfb6ac4fee5a3bb27241721986c021)
=> port rio (#960) to hammer-humble

packages/react-components/lib/tasks/create-task.tsx, packages/react-components/lib/tasks/types/delivery-custom.spec.tsx, packages/react-components/lib/tasks/types/delivery-custom.tsx
Removing cart ID field in double compose delivery task form
=> Remove cart ID fields in double compose delivery form

packages/dashboard/src/managers/resource-manager.ts, packages/react-components/lib/map/circle-shape.tsx
Update default map zoom to fit office world, and fix circle shape robot rotation
* default zoom was too small for office world, changed from 5 to 20
* default robot circle shape was offset by 90 degrees
=> Update default zoom values and default robot shape rotation

packages/dashboard/app-config.json, packages/dashboard/src/app-config.ts, packages/dashboard/src/components/app.tsx, packages/dashboard/src/components/appbar.tsx
* Bring back admin tab and custom tabs
* Make them build-time configurable
=> Adding build-time configuration to bring back custom and admin tabs

packages/dashboard/index.html, packages/dashboard/src/components/rmf-app/rmf-ingress.ts, packages/dashboard/vite.config.ts
* use relative path for icon
* make trajectory server connection optional as core library nodes are sometimes shut down
=> Minor dashboard fixes

packages/dashboard/src/app-config.ts, packages/dashboard/src/util/url.ts
While not explicitly mentioned, vite docs strongly suggests that `base` must end with a trailing slash https://vitejs.dev/config/shared-options#base. With this assumption, we can simplify how we build urls. This assumption is also required to fix favicon path in #989.
=> dashboard: simplify url utils

packages/dashboard/app-config.schema.json, packages/dashboard/src/app-config.ts
1. Add docs.
2. Use inline object over `Record` so that the generated json schema is strictly typed.
=> dashboard: better json schema

packages/dashboard/src/components/map-app.tsx, packages/dashboard/src/components/three-fiber/camera-control.tsx
* Tweak camera target to most negative number to better accommodate almost-orthogonal view for extremely large maps
* refactored camera control to prevent creation of camera every time zoom changes
=> Setting camera target to most negative number to handle arbitrary large maps

packages/dashboard/app-config.schema.json, packages/dashboard/src/app-config.ts, packages/dashboard/src/components/tasks/task-schedule-utils.ts, packages/dashboard/src/components/tasks/task-schedule.tsx, packages/react-components/lib/tasks/create-task.tsx, packages/react-components/lib/tasks/types/compose-clean.tsx, packages/react-components/lib/tasks/types/custom-compose.tsx, packages/react-components/lib/tasks/types/delivery-custom.tsx, packages/react-components/lib/tasks/types/delivery.tsx, packages/react-components/lib/tasks/types/patrol.tsx
This allows users to define a custom schedule event color based on task types
For example, changing `app-config.json` to
```
....
{
"taskDefinitionId": "delivery",
"scheduleEventColor": "red"
},
....
```
will yield,
=> Configurable schedule event color based on task type

packages/dashboard/app-config.schema.json, packages/dashboard/src/app-config.ts, packages/dashboard/src/components/alert-manager.tsx
Configurable audio file URL to be played when alerts occur, no alert audio will be played by default.
Use `alertAudioPath` in the app config, for example
```
{
....,
"alertAudioPath": "https://github.com/adafruit/Adafruit-Sound-Samples/raw/7675c60a47c025ab62f77b699d6460d22bb963b1/sonic-pi/elec_ping.wav",
....
}
```
This can also be a relative path, when the audio file is downloaded to `dashboard/public/resources/elec_ping.wav`
```
{
....,
"alertAudioPath": "/resources/elec_ping.wav",
....
}
```
=> Allow configurable alert audio when alert occurs

eslint.config.mjs, packages/dashboard/app-config.schema.json, packages/dashboard/src/app-config.ts, packages/dashboard/src/components/alert-manager.tsx, packages/dashboard/src/components/map-app.tsx, packages/dashboard/src/components/rmf-app.tsx, packages/dashboard/src/components/robots/robot-summary.tsx, packages/dashboard/src/components/tasks/task-schedule.tsx, packages/dashboard/src/components/tasks/task-summary.tsx
1. fix react hooks eslint config
2. remove docs saying that it must be a .wav file, it should support any format supported by the browser, .wav is highly discouraged because of the filesize.
3. fix new alert element being created with every render.
4. fix other hooks violations
=> dashboard: fix alert audio

packages/dashboard/src/components/rmf-dashboard.tsx
Fix an issue where the tab detection fails to account for the base url.
Fix issue where the "not found" page is not shown on paths below base url that is not defined.
=> dashboard: fix route path

packages/api-server/api_server/app_config.py, packages/api-server/api_server/authenticator.py, packages/api-server/api_server/default_config.py, packages/api-server/api_server/models/user.py, packages/api-server/scripts/test_config.py, packages/dashboard/src/components/appbar.test.tsx, packages/dashboard/src/services/stub-authenticator.ts, pnpm-lock.yaml
Remove the stub authenticator in api server. Now instead of a stub, we support using a secret to verify the jwt, for testing, the frontend hardcodes a token signed with the secret. This brings the test environment closer to prod and allows us to test with other claims in the future (e.g. address, emails, custom claims).
=> api-server: remove stub authenticator

.github/workflows/nightly.yml, README.md
* tagging `jazzy` as `latest` as well
=> Jazzy as latest

packages/rmf-dashboard-framework/src/components/map/text-maker.tsx
Resolves https://github.com/open-rmf/rmf-web/issues/1034
* removes an offset for labels based on text length, it will be more intuitive that the text is left-justified at the center of the rendering
=> Remove offset based on text length

packages/rmf-dashboard-framework/src/components/map/robot-three-maker.tsx
Hello,
In the RMF Web Map, the robot labels appear in the top-left corner of the screen.
I have fixed this by changing the position of the labels. Could you please merge this fix?
Thank you.
=> fixed robots label position.

packages/api-client/package.json, packages/rmf-dashboard-framework/package.json, patches/@react-three__fiber.patch, pnpm-lock.yaml
Address security issue in `vitest`
=> Update vitest to address security issue

pnpm-lock.yaml
Update pnpm lock file to handle `patchedDependencies`.
Resolves the issue faced in deployment template, also fixed by https://github.com/open-rmf/rmf_deployment_template/pull/46
=> Update pnpm lock file to handle patchedDependencies difference
